### ISSUE TITLE
Automatically mark exported episodes/movies as watched in the Kodi library after playback

### ISSUE THREAD

**Issue by zebbe152** [asciidisco/plugin.video.netflix#272] opened 2018-01-10 15:16 UTC
*I'm submitting a ...*
  - [ ] bug report
  - [X] feature request
  - [ ] support request

### Prerequisites

* [X] Are you running the latest version?

### Description

Episodes that have been exported to the local library and are started through the Kodi library are not being marked as watched automatically.

I did some googling and if I'm not mistaken this is a feature that can be implemented into the addon. 

I found this old thread on the subject: 
https://forum.kodi.tv/showthread.php?tid=232334

### Steps to Reproduce

1. Export a show or movie to your local kodi library
2. Watch an episode or movie by starting playback through your Kodi library
3. The episode/movie you just watched is not marked as watched in the Kodi library

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [X] Windows (x86/x64)
* [ ] Linux (ARM)
* [ ] Android

**Comment by caphm** [comment] 2018-01-19 10:12
I have run into the same issue and created a standalone addon for this purpose: [service.strmfilemarker](https://github.com/caphm/kodi-service.strmfilemarker)
You can install it from my improvised repo at [https://github.com/caphm/kodi-repo](https://github.com/caphm/kodi-repo)

Maybe the devs can add this functionality into this addon?

**Comment by zebbe152** [comment] 2018-01-20 19:43
Thanks for the tip. I'll try it out.

**Comment by asciidisco** [comment] 2018-01-22 15:46
Duplicate of: https://github.com/asciidisco/plugin.video.netflix/issues/236

**Closed by asciidisco** 2018-01-22 15:46 UTC
Labels: duplicate
