### ISSUE TITLE
[Core] Incoming data is not properly treated as UTF-8 

### ISSUE THREAD

**Issue by Dis90** [asciidisco/plugin.video.netflix#60] opened 2017-04-18 19:07 UTC
Hi,
Plugin doesn't work if I change my Netflix profile language to finnish. I can choose my profile from list but when I try to click 'My List' or anything else I get 'Netflix error'.

kodi.log http://paste.ubuntu.com/24409195/

Ubuntu: 14.04
Kodi: 2f67109
Inputstream: a7e84de

**Comment by asciidisco** [comment] 2017-04-19 08:09
Thank you for the report. I´ve slightly changed the title, to resemble the root cause. Seems like the incoming values aren't properly UTF-8 encoded during the parsing process. Will be fixed in the next release.

**Comment by asciidisco** [comment] 2017-07-02 19:33
Fixed in 0.11.12

**Closed by asciidisco** 2017-07-02 19:33 UTC
Labels: bug
