### ISSUE TITLE
[Playback] Sony Bravia Android with Netflix plugin -> No playback possible

### ISSUE THREAD

**Issue by Johnbe1234** [asciidisco/plugin.video.netflix#219] opened 2017-10-27 17:40 UTC
I'm submitting a support request

My Kodi boxes are a pair of Sony Bravia KDLxx Android TVs. One older 55" device, the second a newer 4K device. I've successfully got the plugin working on my phone (Samsung S7) and followed pretty much the same methodology, so I'm wondering if there's a fundamental difference with the Sony Android and how they handle encryption.

I'm running 0.12.6 version of the plugin and the nightly 32 bit Kodi v18 datestamped Oct 26. Inputstream.Adaptive is 2.1.5 and enabled. I've not done anything with widevine, as it's all Android. Android is version 7.0, kernel 3.10.79.

I can log into Netflix and search for titles but when I try to play anything I get an error "one or more items failed to play. Check the log for more information about this message". Sometimes I just get the plugin alert that something failed to play. 

I´m using the Netflix Repo
Debug log attached. I don't understand enough but I can see some errors.

[kodi.log](https://github.com/asciidisco/plugin.video.netflix/files/1422916/kodi.log)

Thanks in advance, and apologies if I've omitted anything or posted in the wrong place.

**Comment by asciidisco** [comment] 2017-10-27 19:05
Thank you for the detailed report (would´ve liked it even more if you could´ve used the template provided ;))

You actually chose a very bad day for testing, as Netflix changed their API today & those errors are shadowing some others. So, could you please do me a favour and:

a) Update to version 0.12.7
b) Restart Kodi after that (Note: it probably still won't work after that)
c) Do a debug.log where you straight navigate to one movie/episode & try to play that single one & post the complete debug.log of that operation
d) Navigate to the plugin settings -> Expert -> Click on the ESN field & tell me the content of that field char by char (basically just copy the contents of that field by hand)

I do have a slight idea what the problem could be, but I need to verify it first.

**Comment by Johnbe1234** [comment] 2017-10-27 20:37
Apologies (I thought I had followed the template!)

ESN is NFANDROID1-PRV-SONLYANDROIDTV2017-SONYBRAVIA=4K=GB (for one of them, let me know if you need to know both)

I can't see 0.12.7 in the repository and can't find a way of manually updating it - sorry for being dumb :)

If you don't mind spoon feeding me I'll gladly update it of course.

**Comment by Johnbe1234** [comment] 2017-10-27 21:42
Grrr...
NFANDROID1-PRV-SONYANDROIDTV2017-SONYBRAVIA=4K=GB

**Comment by Uukrull** [comment] 2017-10-28 18:22
@Johnbe1234: Could you post the ESN from your TV Netflix app? (Settings > Get Help >Device)

**Comment by Johnbe1234** [comment] 2017-10-29 10:29
ESN is NFANDROID1-PRV-SONYANDROIDTV2017-SONYBRAVIA=4K=GB  (for one of them, let me know if you need to know both)

**Comment by Johnbe1234** [comment] 2017-10-29 10:38
aahhhh...its different on the Netflix native to the TV, I think I understand now.

It is NFANDROID2-PRV-SONYANDROIDTV2017-SONY=BRAVIA=4K=GB-6566-3CFAB4120A0CBE90AFBDAD121A391047B4498ACB0DE9E1741214C3DF87335AB42

**Comment by Uukrull** [comment] 2017-10-29 12:11
Put this ESN in the options of the addon:

NFANDROID1-PRV-SONYANDROIDTV2017-SONY=BRAVIA=4K=GB

and restart Kodi. It should work after that.

**Comment by asciidisco** [comment] 2017-10-29 12:13
We should take a look at what´s going wrong with the ESN generator here & why it generates a falsy one...

**Comment by Johnbe1234** [comment] 2017-10-29 14:55
No change. Still says unable to play.

**Comment by Uukrull** [comment] 2017-10-29 15:07
Could you check if the file Android/data/org.xbmc.kodi/files/.kodi/userdata/addon_data/plugin.video.netflix/settings.xml has the ESN I posted?

**Comment by asciidisco** [comment] 2017-10-29 15:33
@uukrull Did you maybe mean

‘NFANDROID2-PRV-SONYANDROIDTV2017-SONY=BRAVIA=4K=GB’

instead of

‘NFANDROID1-PRV-SONYANDROIDTV2017-SONY=BRAVIA=4K=GB’ ?

**Comment by Uukrull** [comment] 2017-10-29 16:08
On my Shield and Mecool M8S Pro+, the Netflix apps always show the ESN as NFANDROID2 and the addon as NFANDROID1, and it seems to be the same with the Sony Netflix app.

Just to be sure, I'd also delete the Android/data/org.xbmc.kodi/files/.kodi/userdata/addon_data/service.msl/ folder before launching Kodi.

**Comment by Johnbe1234** [comment] 2017-10-30 18:37
I manually amended settings.xml and it works! Thanks for your help - I presume you want to do some further work but I'm happy it does what I want.

**Comment by choco** [comment] 2017-12-17 11:26
Hi I'm having the same issue on my Sony Bravia Android TV. The Netflix app reports an ESN `NFANDROID2-PRV-SONYANDROIDTV2017-SONY=BRAVIA=4K=GB+otherdata` while the add-on had `NFANDROID1-PRV-SONYANDROIDTV2017-SONY=BRAVIA=4K=GB`. I tried changing the ESN both in the add-on settings and by changing the settings.xml file to `NFANDROID2-PRV-SONYANDROIDTV2017-SONY=BRAVIA=4K=GB` but I'm still getting the same error when I try to play :(
@Johnbe1234 did you add the whole identifier to settings.xml or only `NFANDROID2-PRV-SONYANDROIDTV2017-SONY=BRAVIA=4K=GB` to solve this?

**Comment by asciidisco** [comment] 2018-01-23 15:07
Closing this in favour of https://github.com/asciidisco/plugin.video.netflix/issues/155
The issue is being worked on, I just wanted to sum everything up within one issue.

**Closed by asciidisco** 2018-01-23 15:07 UTC
Labels: android, bug

**Comment by asciidisco** [comment] 2018-01-26 10:15
Could you try to enter this ESN manually in the settings & restart Kodi afterwards?
`NFANDROID1-PRV-SONYANDROIDTV2017-SONYBRAVIA=4K=GB`
