### ISSUE TITLE
NextUp Service compatibility

### ISSUE THREAD

**Issue by kat953162** [asciidisco/plugin.video.netflix#156] opened 2017-09-28 22:13 UTC
I don't use Netflix often. However, one feature that I use on Kodi, as well as Netflix and Prime, is the NextUp option where it will pop up about 30 seconds before the episode ends.

This feature is available as a service addon for Kodi. https://kodi.tv/addon/services/nextup-service-notification

Unfortunately, because episodes aren't viewed as a playlist (or files), it will not show up.

Perhaps this could be developed? It would allow a true "Netflix experience".

**Comment by kat953162** [comment] 2017-09-28 22:22
I should note- the Nextup plugin has a really annoying Postplay screen. In case it makes a difference, the better experience for most would be with it OFF. I am unsure if it is on by default.

**Comment by hawkeyexp** [comment] 2017-10-01 06:22
Seems it needs a fix inside the nextup service addon.

I opened an issue for the dev.

https://github.com/im85288/service.nextup.notification/issues/30

**Comment by hawkeyexp** [comment] 2017-10-06 21:03
Issue can be closed. Netxup sevice got a fix from me which is merged. Only some fine tuning will be done for next release. Problem was not caused by netflix plugin. It was a general prob in nextup service addon when tvshowid is missing like when playing a strm.

**Comment by joaosagrath** [comment] 2017-10-07 11:49
So, this way we don't need to upgrade NextUp?

**Comment by hawkeyexp** [comment] 2017-10-07 16:44
correct - nextup service addon will get this commit with next release and can handle the missing tvshowid.
But note: it is only working for content which was exported by the plugin and is part of the kodi db which is base requirement for nextup service addon.

**Comment by asciidisco** [comment] 2017-10-09 13:59
Closing this, as it´s not related to plugin functionality.
Thanks @hawkeyexp for proposing changes to the service plugin over there.

**Closed by asciidisco** 2017-10-09 13:59 UTC
