### ISSUE TITLE
Netflix error -check log for details

### ISSUE THREAD

**Issue by ASHJG** [asciidisco/plugin.video.netflix#200] opened 2017-10-19 19:43 UTC
*I'm submitting a ...*
  - [x] bug report
  - [ ] feature request
  - [ ] support request

## General infomration
I'm running latest 0.12.2,  Kodi build 18.0Alpha1 git 95762bd 17 Oct on 2 separate RPI2, both had the same problem reported here: https://github.com/asciidisco/plugin.video.netflix/issues/199 after upgrading to 0.12.2 this issue was resolved. however now only one of RPI2 im getting a Netflix error and cant get to the profiles page (the other RPI2 is working as  #expected!?) Tried uninstalling, rebooting, clearing setting etc.. Both RPI are identical in set-up, same version, same addons, same configuration (or so i believe! i can see any differences) 

### Prerequisites

* [x] Are you running the latest version?

### Description

[Description of the bug or feature]
Netflix error when opening Neflix addon
### Steps to Reproduce

1. [First Step]
Open Neflix addon

**Expected behavior:** [What you expected to happen]
show profiles
**Actual behavior:** [What actually happened]
nothing apart from error
## Context (Environment)
RPI2 Kodi 18 (17 oct)
### Installation

* [ ] I installed the plugin via zip from the Releases page
* [x] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [x] Linux (ARM)
* [ ] Android

## Debug log

[kodi.log](https://github.com/asciidisco/plugin.video.netflix/files/1399782/kodi.log)

**Comment by ASHJG** [comment] 2017-10-19 20:05
downgrading to 0.12.0 has seemed to have fixed the issue.

**Comment by aspymid** [comment] 2017-10-20 17:36
I have the same issue. However downgrading to 0.12.0 is a fix that is not solid. After some time it stops working. I am running under the same conditions as above on an RPi3.

The kodi log I get is the following:
13:28:07.073 T:1736438768   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
  - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!                                           
 Error Type: <type 'exceptions.TypeError'>                                           
 Error Contents: int() argument must be a string or a number, not 'NoneType'                                           
 Traceback (most recent call last):                                           
   File "/home/osmc/.kodi/addons/plugin.video.netflix/service.py", line 16, in <module>                                           
     from resources.lib.NetflixHttpRequestHandler import NetflixHttpRequestHandler                                           
   File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/NetflixHttpRequestHandler.py", line 30, in <module>                                           
     netflix_session=NETFLIX_SESSION)                                           
   File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/NetflixHttpSubRessourceHandler.py", line 31, in __init__                                           
     self.prefetch_login()                                           
   File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/NetflixHttpSubRessourceHandler.py", line 42, in prefetch_login                                           
     if self.netflix_session.is_logged_in(account=self.credentials):                                           
   File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/NetflixSession.py", line 241, in is_logged_in                                           
     exp = int(cookies[0][domains][domain][cookie_key].expires)                                           
 TypeError: int() argument must be a string or a number, not 'NoneType'                                           
 -->End of Python script error report<--

**Comment by LtFeroX** [comment] 2017-10-20 17:56
Hi Guys,
I got the same issue as well.
2 days ago everything worked until I started from scratch to build a new LE-RPi with Netflix on it.
Today I tried to install Netflix again, neither from Zip nor from Repository worked for me. Newest Milhouse LE is installed. My Steps:
Libreelec --> Libreelec (Milhouse, Kodi 18) --> Inputstream.Adaptive --> LibWideDevine ( SSH Command) --> Netflix Repository --> Netflix

2/3 Dependencies are installed, the 3. **(Script.Module.Pycryptodome) was unavailable ???**
So I installes it over .zip.
---> Netlix Error : See Log ...

---------------------------------------------------

[01_KODI.log](https://github.com/asciidisco/plugin.video.netflix/files/1402846/01_KODI.log)

> **17:50:12.418 T:1749087120   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: __generate_msl_header() got an unexpected keyword argument 'id_key_request'
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.netflix/service.py", line 16, in <module>
                                                from resources.lib.NetflixHttpRequestHandler import NetflixHttpRequestHandler
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/NetflixHttpRequestHandler.py", line 30, in <module>
                                                netflix_session=NETFLIX_SESSION)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/NetflixHttpSubRessourceHandler.py", line 31, in __init__
                                                self.prefetch_login()
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/NetflixHttpSubRessourceHandler.py", line 50, in prefetch_login
                                                self.kodi_helper.set_esn(self.netflix_session.esn)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/KodiHelper.py", line 224, in set_esn
                                                self.delete_manifest_data()
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/KodiHelper.py", line 233, in delete_manifest_data
                                                msl = MSL(kodi_helper=self)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/MSL.py", line 69, in __init__
                                                self.init_rsa_keys()
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/MSL.py", line 82, in init_rsa_keys
                                                self.__perform_key_handshake()
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/MSL.py", line 635, in __perform_key_handshake
                                                encrypt=False)
                                            TypeError: __generate_msl_header() got an unexpected keyword argument 'id_key_request'
                                            -->End of Python script error report<--**

**Comment by tonyschuite** [comment] 2017-10-20 18:35
same here. have been watching last night, no problems. 
no more login tonight. downgrade to 12.0 worked. 12.1 and 12.2 do not work.

**Comment by MilhouseVH** [comment] 2017-10-20 18:50
> 3. (Script.Module.Pycryptodome) was unavailable ???
pycryptodome is built-in on LibreELEC 8.1.x/9.0- the kodi add-on system is mis-reporting this dependency.

**Comment by LtFeroX** [comment] 2017-10-20 19:02
Thx for the quick reply.

So its not my fault and ill try downgrading to12.0 and wait for a fix !

**Comment by camjac251** [comment] 2017-10-20 19:50
Did downgrading work for you @LtFeroX

**Comment by aspymid** [comment] 2017-10-20 23:36
12.0 is not stable for me. Some movies work other don't.  << It kind of works >>

**Comment by LtFeroX** [comment] 2017-10-21 09:30
0.12.0 Not Working at all for me :/

After putting in my Email and pw i got a request Error and After restarting Netflix it says Error - See Log ...

**Comment by nikagl** [comment] 2017-10-21 10:47
Same here, some work, some don't. Looks like anything in subfolders doesn't work? Or they might (coincidentally) have the same codec? Let us know what you need to troubleshoot this...

**Comment by asciidisco** [comment] 2017-10-21 11:35
@LtFeroX Your issue has nothing todo with the plugin, it´s either your Distro or Kodi version missing the Cryptodome dependency.

For the rest:
Version 0.12.3 should fix the issues, please retest & report.
(You may need to clean your addons userdata in order to be able to retain the functionality)

A few more words: Please do not consider this plugin stable yet. The plan is to release a stable* version when Kodi 18 will be stable/released. So might be another 3 to 5 months since so.
In the meantime, please test & treat this as am Alpha version to test. We need your feedback to stabilise, but things will break from time to time...

*stable: As far as we can call it stable as Netflix has no public API & they can break it anytime without us getting a warning.

**Comment by LtFeroX** [comment] 2017-10-21 11:46
Yea that was my First idea to install the missing dependencie, but how? I tried to install it with a .zip, but its not Working. @MilhouseVH said its already Inside Kodi 18... i got the latest Milhouse Kodi Version and added the Custom Channel for updates... i might try 12.3

**Comment by asciidisco** [comment] 2017-10-21 12:21
@LtFeroX You can't install this dependency like other Python based ones, as it contains OS dependent binary stuff...
It either is a problem in that one particular @MilhouseVH build you´re using (doubt that a bit,a s we might see more reports about this) or something borked on your machine.
Updating the plugin won't help.
My advice would be to use another SD card & try with a fresh system (donwload new latest etc.)

**Comment by LtFeroX** [comment] 2017-10-21 12:30
Thx for ur help! So your advice is to use some of the nightly builds, that you have linked under your Addon ? A friend has no Probleme using a @MilhouseVH Build that is a week old... ill try some older builds and Report then!

**Comment by asciidisco** [comment] 2017-10-21 12:32
@LtFeroX Try to download the same build as your friend uses then, yes. this might be a helpful resource as well: https://github.com/asciidisco/plugin.video.netflix/wiki/Installation

**Comment by nikagl** [comment] 2017-10-21 13:34
@LtFeroX I may be mistaken, but I think I only did this:

1. Download LibreELEC.USB-SD.Creator.Win32.exe and download & install the latest version

2. Pick your source and download the .tar from here:
https://forum.kodi.tv/showthread.php?tid=298462 (x86_64)
https://forum.kodi.tv/showthread.php?tid=298461 (RPi & RPi2/3)

3. Install Widevine using SSH:
curl -Ls http://nmacleod.com/public/libreelec/getwidevine.sh | bash

4. In case you wish to be able to update, set the correct channel:
RPi Zero/RPi1: http://milhouse.libreelec.tv/builds/master/RPi
RPi2/RPi3: http://milhouse.libreelec.tv/builds/master/RPi2
Generic (x86): http://milhouse.libreelec.tv/builds/master/Generic

5. Download netflix repo from here:
https://github.com/asciidisco/plugin.video.netflix

As far as I remember, it work as a charm on RPi, Rpi2, RPi3 and an x86 machine on all of them I tried it.

Note: beta builds so expect issues & haven't tested 0.12.3 yet but is supposed to fix our issue...

**Comment by LtFeroX** [comment] 2017-10-21 13:40
That excactly the Way i did it ... but ill try it again this way.
Thx

**Comment by aspymid** [comment] 2017-10-21 14:17
@asciidisco 
Let me know if I can help. I would like to contribute at least through testing and reporting. I think this plugin will be great! I have been wanting this for a long time!  The reports I post here is to help and I do understand that this software is under development and what that means.  Thanks!

**Comment by asciidisco** [comment] 2017-10-21 14:19
@aspymid Sure. This wasn't meant to be offensive in any way, I just wanted to clarify (again) that this piece of software is yet nothing people can & should rely on :)

Any reports & testing is highly appreciated :)

**Comment by asciidisco** [comment] 2017-10-21 14:21
I´m closing this issue for now, as a few people with similar problems (according to their logs) on the Kodinerds forum have retested this & confirmed that it´s working.
If you´re using version 0.12.4 & do run into the issues mentioned here again, please fell free to reopen.

**Comment by ASHJG** [comment] 2017-10-21 14:21
upgraded to latest 0.12.4 and confirmed issue now solved.

> A few more words: Please do not consider this plugin stable yet. The plan is to release a stable* version when Kodi 18 will be stable/released. So might be another 3 to 5 months since so.
In the meantime, please test & treat this as am Alpha version to test. We need your feedback to stabilise, but things will break from time to time...

Noted and appreciate the hard work, always happy to test.

**Closed by asciidisco** 2017-10-21 14:21 UTC

**Comment by aspymid** [comment] 2017-10-21 14:58
I confirm!  This issue is not present in 0.12.4 ... Thanks!

**Comment by DrCord** [comment] 2017-11-19 18:33
I get this issue on 0.12.7

**Comment by 23d1** [comment] 2018-08-22 05:40
Having a similar issue as @DrCord (script.module.pycryptodome) with the latest version of OSMC and the latest version(s) of the addon, the latest being 0.13.12... Any pointers?

**Comment by caphm** [comment] 2018-08-22 12:55
See #237 
> sudo apt-get install build-essential python-pip
> sudo pip install -U setuptools
> sudo pip install wheel
> sudo pip install pycryptodomex

**Comment by 23d1** [comment] 2018-08-22 17:16
@caphm I actually managed to sort it out. Ran into another issue with the streaming helper not installing, so I ended up manually installing it and now everything works.
