### ISSUE TITLE
Netflix addon working, but videos won't play

### ISSUE THREAD

**Issue by mattreecebentley** [asciidisco/plugin.video.netflix#552] opened 2018-11-27 01:08 UTC
*I'm submitting a ...*
  - [x] bug report
  - [ ] feature request
  - [ ] support request

## General infomration

Browsing catalogue works, video playback was working up until today, as of today no videos will play.
Tried updating to latest nightly and latest repo zip download (.19), no luck.

Other inputstream based plugins like youtube working fine.

### Prerequisites

* [x] Are you running the latest version?

### Steps to Reproduce
Try playing a video.

### Installation

* [x] I installed the plugin via zip from the Releases page
* [ ] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

Win10 1803 x64.

## Debug log
https://pastebin.com/1ZrFsNP6

**Comment by hlashbrooke** [comment] 2018-11-27 05:58
+1 - having the same issue here. It was working last night (about 12 hours ago), but no longer working now. I'm guessing Netflix has changed something again.

**Comment by TVM4iN** [comment] 2018-11-27 08:30
netflix some change

**Comment by caphm** [comment] 2018-11-27 08:32
Duplicate of #550

**Closed by caphm** 2018-11-27 08:32 UTC
