### ISSUE TITLE
Libreelec, video is not playing, or at least not showing up

### ISSUE THREAD

**Issue by luisspuerto** [asciidisco/plugin.video.netflix#286] opened 2018-02-02 17:14 UTC
*I'm submitting a ...*
  - [x] bug report
  - [ ] feature request
  - [x] support request

### Prerequisites

* [x] Are you running the latest version?

### Description

[Description of the bug or feature]

When I start libreelect after a while there is a notification telling that has been an error in Netflix plugging and that I have to check the log. When I try to play the video inside to plugging nothing shows up, but for Kodi something it's playing. I can see it on my remote and on the upper right corner of the screen. 

Sometimes after a while there is message saying that there has been an error in the video or something similar. But I don't know if it's really related. 

### Installation

* [ ] I installed the plugin via zip from the Releases page
* [x] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [x] Linux (ARM)
* [ ] Android

#### Additional informatin on the environment

I have the last build of [Libreelec 9 with Kodi 18 from Mildhouse](https://forum.kodi.tv/showthread.php?tid=298462) and the [Estuary Mod Skin ](https://forum.kodi.tv/showthread.php?tid=306757). 

I'm using a Raspberry Pi 3 Model B.

## Debug log

https://gist.github.com/luisspuerto/6b10dd719cb149342913720a7f1afbe4

* I have more log files: 

https://gist.github.com/0676a84159bd4636e072ebab6f54da95
https://gist.github.com/62b4b48b9925fd68fed517f765dbafe0
https://gist.github.com/a9aa9a0f741075135e2f58ac5b1ed266
https://gist.github.com/700253b0dfced1ff7039dd93daff2bc2

## Other information

I installed very recently on the Pi this Libreelec Alpha and after run `getwidevine.sh` the plugin worked really well. I installed also Estuary Mod Skin and begin to configure several things of the interface and so on and I think I rebooted the Pi several times in the process. Everything worked. Next day I was to check on something and I don't know why I rebooted the Pi again. After that, the error message begin to appear and the video don't work. 

I've tried to uninstall the plugin and reinstall again, but the the same error. 

Any help it's much appreciated. 

### Screenshots

First this message appear just after a 30' of restart the Raspberry Pi
![screenshot001](https://user-images.githubusercontent.com/22882880/35745045-9def212e-084a-11e8-90b5-0b5749acac06.png)

Then, when I go to the plugin interface and I try to play a video it begins to load
![screenshot002](https://user-images.githubusercontent.com/22882880/35745046-9e214604-084a-11e8-87ba-b273629b2646.png)

It makes a really short pause and continue loading. 
![screenshot003](https://user-images.githubusercontent.com/22882880/35745048-9e41cef6-084a-11e8-85cc-0db04c0986df.png)

And then stop loading and nothing happens. 
![screenshot004](https://user-images.githubusercontent.com/22882880/35745049-9e675842-084a-11e8-9fe9-0c63c0fa1293.png)

If I exit the plugin, I can see that for Kodi the video is playing, because in the upper right corner the is the icon of the video playing. No sound, though. 
![screenshot005](https://user-images.githubusercontent.com/22882880/35745050-9e9a91b2-084a-11e8-9305-797cf77672c5.png)

I can stop the video
![screenshot006](https://user-images.githubusercontent.com/22882880/35745051-9ec2a594-084a-11e8-906c-765b33d7a707.png)

I can even rate the video with Trak
![screenshot007](https://user-images.githubusercontent.com/22882880/35745052-9f08a602-084a-11e8-95a5-f0c3378feb9a.png)

**Edit 3rd of February 2018 at 16m:03 UTC** 
This is message about the failed video I was telling you before
![screenshot009](https://user-images.githubusercontent.com/22882880/35768945-439214a8-090c-11e8-99a2-52f7a31a7045.png)

**Comment by gabm** [comment] 2018-02-06 07:32
Very complete bug-report indeed. I have the same setup (RPi3/Libreelec/Milhouse testbuilds) and experience the same problem.. 

I read somewhere that a recent version of libwidevinecdm.so is crashing kodi on ARM but I didnt have any luck to find more information on that..

I'd be happy to provide some logs as well if necessary

**Comment by luisspuerto** [comment] 2018-02-06 07:37
I decided to delete everything and reinstall. I really think that perhaps the skin has also something to do with all of these. Now it's working again. I just install the netflix plugin and trak. Nothing else. 

Anyhow, the plugin works great, but the pi overheat a lot, even with a heat sink. I'm waiting for a box with a small fan on it.

**Comment by MilhouseVH** [comment] 2018-02-06 07:46
This is a duplicate of https://github.com/asciidisco/plugin.video.netflix/issues/196.

Rebooting normally fixes the issue.

**Comment by luisspuerto** [comment] 2018-02-06 07:55
@MilhouseVH we rebooted plenty of times always with the same problem

**Comment by gabm** [comment] 2018-02-06 07:58
yep, It seems I have another problem.. not sure whether its exactly the same as @luisspuerto, but its basically saying "playing" but neither sound nor video appear... in the logs everything seems normal though, no apparent crashes or errors showing up ...

**Comment by luisspuerto** [comment] 2018-02-06 08:00
It's true that I set up the Estuary mod skin 2, put netflix in the main menu and set up a couple of widgets. I can try to reproduce, since I wiped out everything and reinstalled.

**Comment by MilhouseVH** [comment] 2018-02-06 08:00
> @MilhouseVH we rebooted plenty of times always with the same result

It can be a bit random, but your posted logs all have the "Connection refused" error so I'm pretty sure your issue is #196. It's unusual for it to happen _every_ time, though.

**Comment by luisspuerto** [comment] 2018-02-06 08:01
@MilhouseVH But, is it usually related to the widgets?

**Comment by MilhouseVH** [comment] 2018-02-06 08:03
Couldn't tell you. I use stock Estuary and Kodi 18 and get this issue from time to time (not often though). That's about all I can tell you about it - I haven't looked into what causes it, I'm just aware there's already an issue discussing it.

**Comment by luisspuerto** [comment] 2018-02-06 08:07
OK! 

Thanks a lot for your insights! It's a lot of help. I try to reproduce again the issue and check if can be fixed removing the widgets. 

Thanks!

**Comment by hauemric** [comment] 2018-02-06 21:49
Hey people,

same issue here, rapi 3, libreelec, I reinstalled everything fresh. First addon I put on was the Ascidisco Netflix and it worked like a charm. After I was finished with setting up my Kodi system and installing all other addons, it stopped working.

I raised this issue already in a previous post (https://github.com/asciidisco/plugin.video.netflix/issues/274)
Did anyone come across a solution which prevents a complete wipe and reinstall?

Best

**Comment by luisspuerto** [comment] 2018-02-07 06:49
@hauemric do you have widgets or something like that? or perhaps you've also changed the skin?

**Comment by gabm** [comment] 2018-02-07 07:29
I found one problem in my setup where I had to disable OMX acceleration and enable MMAL (which I believe is deafult, but I changed it to try..).. Before the playback would start, but not show any image on the screen. Now everything seems to work - except for the raspbi getting pretty hot..

**Comment by hauemric** [comment] 2018-02-10 21:26
@gabm

Sweeeeeeet! Thanks for your reply!
Disabling the OMX acceleration did it - works like a charm now on first sight!!!

**Comment by hauemric** [comment] 2018-02-10 21:27
@luispuerto

Thanks for your message. Widgets and Skins weren’t the source if the prob

**Comment by t3uch1** [comment] 2018-02-18 15:29
I have the same problem as you but I can not find the setting to disable

**Comment by caphm** [comment] 2018-09-04 08:49
I assume this issue has been resolved, as there has not been any further activity. Feel free to reopen if the issue still persists.

**Closed by caphm** 2018-09-04 08:49 UTC
