### ISSUE TITLE
Some tv shows/movie on "my list" don't appear

### ISSUE THREAD

**Issue by joaosagrath** [asciidisco/plugin.video.netflix#61] opened 2017-04-19 16:16 UTC
Yesterday i''ve noted that some tv shows/movies don't appear. I've checked on netflix website, and, yes, it on my list, but, in addon when I enter on "my list", the item is not there. If, in the website I remove, and re-add to my list, the item appear on the addon.

Don't know if it's a bug or something else, but it's better to report :)

**Comment by asciidisco** [comment] 2017-04-20 09:15
@joaosagrath Could it be related to this? https://github.com/asciidisco/plugin.video.netflix/issues/42

**Comment by joaosagrath** [comment] 2017-04-20 17:03
Yes, I think it´s relate... don´t count how manu itens I have at the moment. 
But, if I try to change a little, only to test the impact, need only to change this value?

**Comment by asciidisco** [comment] 2017-04-20 19:04
@joaosagrath Yes, bump list_to to somthing like 50 or 70, that should suffice.

**Comment by asciidisco** [comment] 2017-04-27 08:38
@joaosagrath I´ve seen that anything beyond a max. value of 50 returns a 417 status code from Netflix. Have you had a chance to bump the value on your side to 50 & check if that´s the issue?
In my wip branch, I´ve set the value to 50 now, so if that´s the issue it should be solved in the next release.

**Comment by joaosagrath** [comment] 2017-04-27 11:28
@asciidisco First I´ve bumped to 70 the value, but, don´t work, the lists simple don´t load. Then, bumped to 50 and nothing, the lists don´t load.

folow the log:

https://pastebin.com/xwLgHCet

**Comment by asciidisco** [comment] 2017-07-02 20:07
@joaosagrath I´ve tested it & 26 is the maximum value that gets accepted, therefor I need to change the code to paginate or to do multiple requests...

Nevertheless, I´m closing this, as this is a duplicate of: https://github.com/asciidisco/plugin.video.netflix/issues/42

**Closed by asciidisco** 2017-07-02 20:07 UTC
Labels: bug, possible duplicate
