### ISSUE TITLE
Doesn't work on rpi 3 B+

### ISSUE THREAD

**Issue by arpruss** [asciidisco/plugin.video.netflix#553] opened 2018-11-27 04:32 UTC
*I'm submitting a ...*
  - [X] bug report
  - [ ] feature request
  - [ ] support request

## General infomration

I can see the catalog but no streams play. I tried 0.13.16, 0.13.17, 0.13.18, 0.13.19 and the unofficial 0.13.20.

I get a "Connection refused" in the log.

### Prerequisites

* [X] Are you running the latest version?

Yes.

### Description

Depending on version, I get an error message or no error message, but in no case have I been able to get any stream to play.

### Steps to Reproduce

1. Install add-on on Raspberry PI 3 B+ with Raspbian Stretch and Kodi 0.18 beta 4.
2. Try to play a stream.

### Installation

* [X] I installed the plugin via zip from the Releases page
* [X] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [X] Linux (ARM)
* [ ] Android

#### Additional informatin on the environment

Raspberry PI 3 B+ 
Raspbian Stretch
Composite TV output
Kodi 18 beta 4

## Debug log

Here is the log from 0.13.19: http://pruss.mobi/dl/kodi-netflix-0.13.19.log
http://pruss.mobi/dl/manifest-0.13.19.json

**Comment by arpruss** [comment] 2018-11-27 04:53
Also no luck with Kodi 18 rc1.

**Comment by hlashbrooke** [comment] 2018-11-27 05:58
+1 - having the same issue here. It was working last night (about 12 hours ago), but no longer working now. I'm guessing Netflix has changed something again.

**Comment by jmeloranta** [comment] 2018-11-27 06:00
Worked for me on 3 B+ until today.... (but this is not 3 B+ related problem - something changed at netflix).

**Comment by caphm** [comment] 2018-11-27 08:32
Duplicate of #550

**Closed by caphm** 2018-11-27 08:32 UTC

**Comment by hlashbrooke** [comment] 2018-11-27 08:46
This issue, as well as #552 are not duplicates of #550 as this is a different problem that has been caused by Netflix changing something on their side.

**Comment by Essam315** [comment] 2018-11-27 08:53
@caphm
This issue is not Duplicate, its a new problem caused by Netflix.

 550 has fixed here.
https://github.com/asciidisco/plugin.video.netflix/commit/5d363569b025247f5005a2266e69efddb1476cc7

**Comment by gruhalski** [comment] 2018-11-30 20:56
Looking at the manifest.json file attached, I'm experiencing the same issue on Ubuntu.
Is there anyone looking into that?
