### ISSUE TITLE
Netflix Error when I try to open the add-on

### ISSUE THREAD

**Issue by mon1623** [asciidisco/plugin.video.netflix#346] opened 2018-05-02 18:04 UTC
*I'm submitting a ...*
  - [ ] bug report
  - [ ] feature request
  - [x] support request

## General infomration
Android 6.0.1 Kodi 18 last nightlie
### Prerequisites

* [x] Are you running the latest version?

### Description

I can't open the add-on, I get an error "Netflix Error, check the log for more information"

### Steps to Reproduce

1. I Installed the repository 
2. I Enabled Input Stream
3. I Installed the add-on and tried to get in

**Expected behavior:** Enter into the addon

**Actual behavior:** Netflix Error, check the log for more information

### Installation

* [ ] I installed the plugin via zip from the Releases page
* [x] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [ ] Linux (ARM)
* [x] Android

## Debug log
Kodi Log
https://pastebin.com/D2p0gZMp

**Comment by peak3d** [comment] 2018-05-03 13:30
Pls. provide a full log

**Comment by mon1623** [comment] 2018-05-03 16:00
Here is the [full log](https://pastebin.com/0cLVJaSX)

**Comment by liberty-developer** [comment] 2018-05-03 16:58
Can you pls. enable debug logging?
A Debug log means always Debug logging" in settings enabled.
Pls. make sure, that component debugging is off. Thanx

**Comment by mon1623** [comment] 2018-05-03 17:28
Sorry here is the [debug log](https://pastebin.com/UEC0asQm)

**Comment by mrfixit3000** [comment] 2018-05-03 19:16
I am also experiencing this issue. Just to confirm he isn't alone.

**Comment by ido-ran** [comment] 2018-05-03 20:03
I also experiencing this issue. This is the error with debug logging on:

```
22:59:01.968 T:1440736112   DEBUG: [Netflix] Started (Version 0.13.2)
22:59:01.968 T:1440736112   DEBUG: [Netflix] "Navigation::router" called with arguments :paramstring = :
22:59:01.968 T:1440736112   DEBUG: [Netflix] "Navigation::before_routing_action" called with arguments :params = {}:
22:59:01.974 T:1432343408   DEBUG: CWebServer[80]: request received for /?method=is_logged_in
22:59:01.978 T:1440736112   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'urllib2.HTTPError'>
                                            Error Contents: HTTP Error 401: Unauthorized
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.netflix/addon.py", line 33, in <module>
                                                NAVIGATION.router(paramstring=REQUEST_PARAMS)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/utils.py", line 45, in wrapped
                                                result = func(*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/Navigation.py", line 96, in router
                                                options = self.before_routing_action(params=params)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/utils.py", line 45, in wrapped
                                                result = func(*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/Navigation.py", line 794, in before_routing_action
                                                'method': 'is_logged_in'}))
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/Navigation.py", line 978, in call_netflix_service
                                                data = urllib2.urlopen(full_url).read(opener)
                                              File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
                                              File "/usr/lib/python2.7/urllib2.py", line 435, in open
                                              File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
                                              File "/usr/lib/python2.7/urllib2.py", line 473, in error
                                              File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
                                              File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
                                            HTTPError: HTTP Error 401: Unauthorized
                                            -->End of Python script error report<--
22:59:01.978 T:1440736112   DEBUG: onExecutionDone(77, /storage/.kodi/addons/plugin.video.netflix/addon.py)
22:59:02.018 T:1940197968   DEBUG: ------ Window Init (DialogNotification.xml) ------
22:59:02.024 T:1940197968   DEBUG: GLES: Extension Support Test - GL_EXT_texture_format_BGRA8888 YES
22:59:02.272 T:1440736112 WARNING: CPythonInvoker(77, /storage/.kodi/addons/plugin.video.netflix/addon.py): the python script "/storage/.kodi/addons/plugin.video.netflix/addon.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon9xbmcaddon5AddonE

```

**Comment by liberty-developer** [comment] 2018-05-04 12:32
Not sure whats the root cause of those different issues, for me on Win there is a change how NX provides profiles -> fixed in branch profiles.

Would be great if you can update / logout (in settings) and login again.

**Comment by ido-ran** [comment] 2018-05-05 04:36
I try both logout and switch account but neither helped.

Ido

**Comment by cy8aer** [comment] 2018-05-05 10:30
same problem with Libreelec Milhouse-9.0 - #0504

**Comment by cy8aer** [comment] 2018-05-05 11:06
It works with Milhouse-9.0 - #0429 - there is a problems with later Milhouse builds. Same problems like with the streaming bug #342.

**Comment by liberty-developer** [comment] 2018-05-05 14:58
@ido-ran from netflix addon issues should be sorted out with 0.13.3, but there are issues with the current kodi / mmal rendering path. Can you confirm, that the python issues are gone with 0.13.3 ?

**Comment by hbbernardo** [comment] 2018-05-06 01:41
Where can I download the 0.13.3 version?
I looked into the repository and isn't there. 
I am also having this issues as well.

**Comment by ido-ran** [comment] 2018-05-07 10:51
I've solved the issue by [installing the latest LibreELEC](https://github.com/asciidisco/plugin.video.netflix/issues/333#issuecomment-385794902)

**Comment by liberty-developer** [comment] 2018-06-10 16:34
can we close this issue? login / playback issues should be slved with 0.13.8

**Comment by asciidisco** [comment] 2018-08-29 09:14
Closing as there is no further feedback, seems like the issues have been resolved.

**Closed by asciidisco** 2018-08-29 09:14 UTC
