### ISSUE TITLE
Raspberry Pi compatibility

### ISSUE THREAD

**Issue by giubari** [asciidisco/plugin.video.netflix#28] opened 2017-03-29 19:33 UTC
Any way to make it work (with all dependencies) on Raspberry Pi 3?

**Comment by asciidisco** [comment] 2017-03-29 20:36
At the moment, no. The problem is not the plugin itself, but the way the rendering architecture in either inputstream.adaptive or Kodi Agile is set up. This is above my understanding too,  but what I grasped from conversations with others is, that the RPI needs a different implementation of certain things due to its different frame buffer architecture (for someone actually know how this stuff works, this might read like total b******t but, yeah, lets keep it that way).

Long story short, I´ve heard of a working fork for the RPI which will never be public, instead, all efforts are put in merging those changes into Kodi Agile directly in a way that it complies with Kodis rules on how such stuff needs to be implemented. This might take some more weeks, but it´s very likely that we´ll end up with a version working on the RPI which most probably will be able to render 720p video & 5.1 audio. If we´re lucky & all works well, we might even end up with 1080 on the PI.

**Comment by cyraid** [comment] 2017-06-15 17:32
Any way to track the progress? Or maybe give someone a hand? I'm not afraid to get my hands dirty if it's to support something I use.

**Comment by asciidisco** [comment] 2017-06-15 17:42
@cyraid The work is basically done. At the moment it´s mostly merging stuff into the "regular" Kodi 18 repo, as well as rewriting parts if the Kodi maintainers do not agree with something in the code to be merged. I believe it´s a matter of weeks now until the needed changes are in Kodi, but I´m not part of the team/people who do actually work on this.

**Comment by giubari** [comment] 2017-06-16 10:01
@asciidisco this is really a great news. Kodi Community is pushing on DRM and official content and plugins and trying to abandon illegal content plugins this would be the perfect way to do it. Today the only way for me to watch my Netflix subscription content is via external addon like TVMC and others.

**Comment by renatoriolino** [comment] 2017-06-22 12:19
@asciidisco Is it possible already to us test it?  I'm confortable to git push development version of LE with kodi 18 and compile.  Is this enough or I would need to apply some patches too? Thanks

**Comment by leleobhz** [comment] 2017-06-25 15:11
Hello,

As a effort to test and share results to help development, I've used the following combination: 

* http://milhouse.libreelec.tv/builds/master/RPi2/LibreELEC-RPi2.arm-8.0-Milhouse-20160601210321-%230601-gb4f3545.tar
* https://www.kodinerds.net/index.php/Thread/51486-Kodi-17-Inputstream-HowTo-AddOns-f%C3%BCr-Kodi-17-ab-Beta-6-aktuelle-Git-builds-Updat/?postID=333953#post333953 (Running the "_curl -Ls http://nmacleod.com/public/libreelec/getwidevine.sh -o /tmp/getwidevine.sh && sh /tmp/getwidevine.sh_" in Raspberry)
* Latest master from git at this date.

With this combination, i got the following crashlog: [kodi_crashlog_20170625150339.log.zip](https://github.com/asciidisco/plugin.video.netflix/files/1100398/kodi_crashlog_20170625150339.log.zip)

It's expected? There is something new I can try?

Thanks!

**Comment by marcelveldt** [comment] 2017-06-25 15:15
First of all, the plugin is currently completely broken due to changes at Netflix. Besides that,  a Milhouse build for Libreelec is based on Kodi master and not the Agile branch/fork.

You'll have to compile LibreElec yourself with the Agile code merged in

**Comment by leleobhz** [comment] 2017-06-25 15:35
@marcelveldt - Sorry to ask, but what is the difference from Agile to Master?

**Comment by marcelveldt** [comment] 2017-06-25 15:37
A lot, for example the ability to use the new input stream  Adaptive with support for decrypting which is the base to watch the Netflix content

**Comment by Uukrull** [comment] 2017-06-25 16:03
That's not true anymore. Since this [PR](https://github.com/xbmc/xbmc/pull/12325), you can use Kodi master and inputstream.adaptive master (tested on Windows with the Amazon addon)

**Comment by cyraid** [comment] 2017-06-26 06:06
So now it'll build on raspberry pi 3? Or does there still need to be changes made?

**Comment by marcelveldt** [comment] 2017-06-26 06:39
@Uukrull oh wow that's some amazing news. Now only we'll have to wait until the netflix add-on is fixed again.

**Comment by Uukrull** [comment] 2017-06-26 07:58
@cyraid: you still have to compile the repo from liberty-developer for [inputstream.adaptive](https://github.com/liberty-developer/inputstream.adaptive) and wvdecrypter.

**Comment by marcelveldt** [comment] 2017-06-26 08:30
@Uukrull what did you do to get the amazon add-on working for your country ? Mine is giving me errors about the geo lock all the time so there must be some code in the add-on to define which catalog it uses. I'm in the Netherlands btw.

**Comment by Uukrull** [comment] 2017-06-26 09:16
@marcelveldt AFAIK the Amazon addon only supports UK, DE, JP and USA regions. I live in Spain but I can use Getflix to get those regions working. Check this for more info: https://github.com/Sandmann79/xbmc/issues/22

**Comment by asciidisco** [comment] 2017-07-02 19:31
Works with Inputstream v2, Kodi 18 Nightly & v0.11.12 of the Netflix Plugin. Therefor closing this.

**Closed by asciidisco** 2017-07-02 19:31 UTC
Labels: bug, Netflix API, question

**Comment by lfarkas** [comment] 2017-07-13 14:29
anybody has any experience with this plugin on  Raspberry Pi 2? I've tried it and it's working, but very slow and choopy so it seems the hardware is not enough to play back the netflix streams.

**Comment by asciidisco** [comment] 2017-07-13 14:32
@lfarkas I´ve heard that it should be enough for SD quality (480p), which seems likely as the PI 3 can do 720p but not 1080p. We need to use software encoding on everything other than Android, so we´ll probably have no chance to do something about this.

**Comment by leleobhz** [comment] 2017-07-13 14:35
Maybe with VC-1 hardware decoder with key?

**Comment by lfarkas** [comment] 2017-07-13 14:35
@asciidisco is there any change to do the same hardware encoding as on android? with this restriction it'd be useful to add as a FAQ point.

**Comment by asciidisco** [comment] 2017-07-13 14:38
@lfarkas The Widevine Library extracted from the browser needs to be used (that´s the thing that does the decoding & the DRM stuff). It only can do software decoding.
Regarding the FAQ, sure send a PR with a link to what I´ve posted above.

**Comment by lfarkas** [comment] 2017-07-17 15:34
I've tested it with Pi 2 and Pi 3. none of them are able to play a netflix video 720p h264 stream. the strange thing it has no cpu load during the playback (10-20%) but it's still choopy lagging and totally unusable.

**Comment by irgendwie** [comment] 2017-07-17 16:36
@lfarkas I can confirm this for **1080p** streams, 720p is working as expected for me (RPi3).
I'm using the libreelec builds of Milhouse (https://forum.kodi.tv/showthread.php?tid=298461) with current master version of this plugin.

**Comment by lfarkas** [comment] 2017-07-17 17:04
ok i've tested it with build #712 it's not working. now i've tested it with build #716 it's working. although the usb ports are not working on Pi3 while working on Pi2 but it's a bug of libreelc not this plugin.

**Comment by MilhouseVH** [comment] 2017-07-17 18:23
@lfarkas USB ports are working fine on RPi3, there's been no other reported issues on the forum (from about 250 testers). I've a keyboard, IR dongle and 32GB storage connected to my RPi3. If you've got an issue with USB post your details in the [Kodi forum thread](https://forum.kodi.tv/showthread.php?tid=298461).

**Comment by tzwn** [comment] 2017-07-18 06:55
@lfarkas @MilhouseVH USB is working fine on my Pi2 and Pi3 with #0716.

**Comment by DaVinci0072** [comment] 2017-08-01 03:16
Works on build #0713, RPi3.  

Max smooth video stream : h264, 720x480, 2314240 bps

**Comment by cyraid** [comment] 2017-08-01 03:23
I had some good smooth video with 720p on rpi3.. but the temperature icon comes up.. looks like I'll have to get a fan+heatsink..

**Comment by jet86** [comment] 2017-08-01 05:49
Yes I've been getting the temperature icon and it begins stuttering when watching at 720p for any period of time. I think a heatsink and/or fan might be the way to go (I don't have them yet either).

**Comment by tzwn** [comment] 2017-08-01 17:29
A good alternative would be a case, which absorbs and dissipates the waste heat from the SoC - passive cooling.

I highly recommend the [Flirc case](https://flirc.tv/more/raspberry-pi-case) - best in the new version adapted for the Raspberry Pi 3.

**Comment by jet86** [comment] 2017-08-02 00:29
Most cases actually tend to contain the heat, not dissipate it, which actually exacerbates the issue. My Pi runs cooler out of its case than in it. The Flirc Case does look pretty good since it effectively is the heatsink as well as the case, but just wanted to point out that most cases aren't designed to dissipate heat.

**Comment by Xandaros** [comment] 2017-11-05 18:28
This issue is linked in the FAQ section of the readme, but I'm a bit confused. Does it work on an RPi now or not?

**Comment by pinoelefante** [comment] 2017-11-05 18:29
it works

**Comment by laclaro** [comment] 2017-12-24 10:32
Some time ago, I used an rpi3 to test the Netflix addon (https://laclaro.wordpress.com/2017/10/14/rpi-streaming-station-with-amazon-instant-video-and-netflix/). It runs smoothly for 720p videos. However, I claimed that you will need the license keys for this.

If I got it right  DRM decoding and GPU acceleration are two different things and with inputstream the GPU cannot be used and purchasing codec licenses will not change that. Is this correct and will it maybe be possible in the future?

Best

**Comment by Tr4il** [comment] 2017-12-25 20:05
@asciidisco You might want to remove the link to this issue from the faq

**Comment by ndm13** [comment] 2018-03-26 06:10
Do we still need to download nightly builds to get this to work? If so, is there a way to track progress until these updates get officially released? Are all the steps on the wiki still required, or have some of them been slipstreamed or superceded?

**Comment by ddlandim** [comment] 2018-06-20 14:50
In my Raspberry Pi 0w, when i will play a video, the widevine installation starts, but i got a error saying that my architeture is not compatible.

**Comment by asciidisco** [comment] 2018-06-20 14:53
@ddlandim Which is correct, there is no widevine library that is compatible with RPI0 & RPI1, only RPI2 & RPI3 do work. Aside from that, the Pi Zero wouldn't have enough computing power to do software decoding/decrypting anyways.

**Comment by ddlandim** [comment] 2018-06-20 15:24
I got it, thanks. I thought that note below, which you wrote in the plugin readme, was for this case.

"The link to download the Widevine Libary for none ARM Systems can be found in the Firefox Sources & needs to be placed in the cdm folder in special://home."

**Comment by padok** [comment] 2018-10-21 18:58
If you turn the question around, how much computing power would you need to have to play 1080p (or 4k in the future) fluently? 

There are also alternative fruity computers.

| Board            | CPU Cores | CPU Freq | HDMI    | Tested        |
|------------------|-----------|----------|---------|---------------|
| Rasberry Pi 3 B  | 4         | 1.2GHz   | 1200P60 | 720p playback |
| Orange Pi Plus 2 | 4         | 1.5GHz   | 4KP30 | ?             |
| Banana PI M3     | 8         | 1.8GHz   | 1200P60 | ?             |

**Comment by pierregermain** [comment] 2019-06-09 14:03
Installing [Input Stream Adaptive](https://kodi.wiki/view/Add-on:InputStream_Adaptive) and then saying yes to all the disclaimers and accepting installing other 3rd party libraries (Widevine and Chrome OS recovery image and others) this plugin works right now on RPI 2. Thanks for your hard work! My son is happy now.

**Comment by GunnarSpawn** [comment] 2019-12-14 03:29
^^^^^^^^^^^^^^ Second this working on December 13th. I just had to setup the input streams adaptive addon (sudo apt-get install kodi-inputstream-adaptive) and its working on the kodi I built atop raspbian via sudo apt-get install kodi  or sudo apt-get install kodi-standalone on raspbian buster pi 4b 2gb mem!

**Comment by gergolippai** [comment] 2019-12-26 18:17
one more success story, i also got it working, using the alternative repo here: https://github.com/CastagnaIT/plugin.video.netflix
InputStream-Adaptive seems to be default in OSMC at least (2019.11-1, Kodi 18.5), but I had to go through some add'l hoops to install pycryptodomex using this little tutorial: https://github.com/asciidisco/plugin.video.netflix/issues/665#issuecomment-483453676

my kids can now watch that horrible Netflix show with the mermaids in it! :)

**Comment by Wolfsrabe** [comment] 2020-02-07 21:20
I experience short audio dropouts using netflix addon with Kodi 18.5 (via the latest LibreELEC) on a RPI 4. I thought, it would help to set the resolution down to 720p but the audio dropouts keep. I dont now what i can do here.
