### ISSUE TITLE
Unable to search anything on the app

### ISSUE THREAD

**Issue by nolsen42** [asciidisco/plugin.video.netflix#418] opened 2018-06-27 00:17 UTC
*I'm submitting a ...*
  - [X] bug report
  - [ ] feature request
  - [ ] support request

### Prerequisites

* [X] Are you running the latest version?

### Description

[Description of the bug or feature]

### Steps to Reproduce

1. Get on Netflix
2. Log into your user (if you have multi-users)
3. Search something.

**Expected behavior:** You find stuff

**Actual behavior:** An error happens

### Installation

* [ ] I installed the plugin via zip from the Releases page
* [X] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [X] Linux (ARM)
* [ ] Android

#### Additional informatin on the environment

I'm running the LATEST version of librelec test build for the raspberry pi.

## Debug log

https://paste.nolsen.xyz/?f8faebe7244a3219#3mzXbbOsDeiPWxOvCkuT2y6BShBWIkWCuGfKmc2VUbI=

**Comment by jackmort37** [comment] 2018-07-06 11:00
Same kind of issue here, when trying to browse the "Top recommended".

Log is quite similar : https://pastebin.com/de5aqTa2

**Comment by caphm** [comment] 2018-08-30 13:55
Duplicate of #254

**Closed by caphm** 2018-08-30 13:55 UTC
