### ISSUE TITLE
Netflix add-on not turning on

### ISSUE THREAD

**Issue by lkord** [asciidisco/plugin.video.netflix#308] opened 2018-03-10 17:39 UTC
*I'm submitting a ...*
  - [x] bug report
  - [ ] feature request
  - [ ] support request

## General information
Error when trying to switch on Netflix add-on

### Prerequisites
Installed Netflix add-on
* [ ] Are you running the latest version?
0.12.7
### Description

Error when trying to switch on Netflix add-on

### Steps to Reproduce

1. Click Netflix Icon

**Expected behavior:** Open add-on

**Actual behavior:** Error info - check the log

## Context (Environment)
RPi3 OSMC kodi 18 alpha
### Installation

* [x] I installed the plugin via zip from the Releases page
* [ ] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [x] Linux (ARM)
* [ ] Android

#### Additional informatin on the environment

n/a

## Debug log

18:26:52.187 T:1821778672   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ValueError'>
                                            Error Contents: No JSON object could be decoded
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.netflix/addon.py", line 42, in <module>
                                                NAVIGATION.router(paramstring=REQUEST_PARAMS)
                                              File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/utils.py", line 45, in wrapped
                                                result = func(*args, **kwargs)
                                              File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/Navigation.py", line 85, in router
                                                options = self.before_routing_action(params=params)
                                              File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/utils.py", line 45, in wrapped
                                                result = func(*args, **kwargs)
                                              File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/Navigation.py", line 708, in before_routing_action
                                                'method': 'is_logged_in'}))
                                              File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/Navigation.py", line 884, in call_netflix_service
                                                parsed_json = json.loads(data)
                                              File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
                                                return _default_decoder.decode(s)
                                              File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
                                                obj, end = self.raw_decode(s, idx=_w(s, 0).end())
                                              File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
                                                raise ValueError("No JSON object could be decoded")
                                            ValueError: No JSON object could be decoded
                                            -->End of Python script error report<--
18:26:52.218 T:1922424672   ERROR: GetDirectory - Error getting plugin://plugin.video.netflix/
18:26:52.219 T:1922424672   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.netflix/) failed

**Comment by zerolab** [comment] 2018-03-17 21:34
#311 is a duplicate of this, but has a good thread.
#312 is the PR with the fix

**Closed** 2018-03-18 09:46 UTC

**Comment by fredistehboss** [comment] 2018-03-23 14:24
This did not fix this issue for me.
Windows 10
Kodi 18 Leia "KodiSetup-20180322-d880ef25-master-x64.exe" [March-23-2018]

LOG:
[kodi.log](https://github.com/asciidisco/plugin.video.netflix/files/1841832/kodi.log)

**Comment by pszi1ard** [comment] 2018-12-29 22:16
I'm also still getting the issue, running OSMC on rpi3, log content:
```
23:11:18.492 T:1496834800   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ValueError'>
                                            Error Contents: No JSON object could be decoded
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.netflix/addon.py", line 33, in <module>
                                                NAVIGATION.router(paramstring=REQUEST_PARAMS)
                                              File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/utils.py", line 60, in wrapped
                                                result = func(*args, **kwargs)
                                              File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/Navigation.py", line 123, in router
                                                options = self.before_routing_action(params=params)
                                              File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/utils.py", line 60, in wrapped
                                                result = func(*args, **kwargs)
                                              File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/Navigation.py", line 867, in before_routing_action
                                                'method': 'is_logged_in'}))
                                              File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/Navigation.py", line 1054, in call_netflix_service
                                                parsed_json = json.loads(data, object_pairs_hook=OrderedDict)
                                              File "/usr/lib/python2.7/json/__init__.py", line 352, in loads
                                                return cls(encoding=encoding, **kw).decode(s)
                                              File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
                                                obj, end = self.raw_decode(s, idx=_w(s, 0).end())
                                              File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
                                                raise ValueError("No JSON object could be decoded")
                                            ValueError: No JSON object could be decoded
                                            -->End of Python script error report<--
23:11:18.674 T:1496834800 WARNING: CPythonInvoker(11, /home/osmc/.kodi/addons/plugin.video.netflix/addon.py): the python script "/home/osmc/.kodi/addons/plugin.video.netflix/addon.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon9xbmcaddon5AddonE
23:11:18.690 T:1608512240   ERROR: GetDirectory - Error getting plugin://plugin.video.netflix/
23:11:18.691 T:1917726720   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.netflix/) failed
```

**Comment by lutel** [comment] 2019-01-27 21:57
Same issue here, this bug shouldn't be closed i guess

**Comment by lutel** [comment] 2019-01-27 21:59
@zerolab could you open this issue?
