### ISSUE TITLE
No video or audio playback on INTEL MESA

### ISSUE THREAD

**Issue by ArturPortella** [asciidisco/plugin.video.netflix#546] opened 2018-11-21 16:48 UTC
*I'm submitting a ...*
  - [ ] bug report
  - [ ] feature request
  - [X] support request

## General infomration
Using Zotac ZBOX ID13
KODI 18.0-BETA5 LEIA
LibreELEC (official): 8.90.007 9.0 (kernel: Linux 4.19.0)

GPU: Mesa DRI Intel(R) Pineview
1366x768@60.01Hz - Full Screen
OpenGL Vendor: Intel Open Source Technology Center
OpenGL Version: Intel Open Source Technology Center
OpenGL Version: 1.4 Mesa 18.2.4

### Prerequisites

* [Y] Are you running the latest version?

### Description

UI Works like a charm, when trying to play a title, it starts loading (spinning disk in mid of screen) and nothing happens.

### Steps to Reproduce

1. Open Netflix ADDON
2. Select any title and try to play it
3. Nothing happens

### Installation

* [X] I installed the plugin via zip from the Releases page
* [X] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [X] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [ ] Linux (ARM)
* [ ] Android

#### Additional informatin on the environment

Using LibreELEC v18 Leia

## Debug log

https://pastebin.com/DpDKsq4n

## Other information

When looking at logfile, I've noticed:

### _16:03:42.170 T:140698441455360  NOTICE: Creating InputStream
16:03:42.305 T:140698441455360   ERROR: GetDirectory - Error getting /usr/lib/kodi/addons/inputstream.adaptive/
16:03:43.523 T:140698498103040   ERROR: Traceback (most recent call last):
16:03:43.524 T:140698498103040   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
16:03:43.525 T:140698498103040   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
16:03:43.525 T:140698498103040   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
16:03:43.526 T:140698498103040   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 652, in __init__
16:03:43.526 T:140698498103040   ERROR:   File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
16:03:43.526 T:140698498103040   ERROR:   File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
16:03:43.526 T:140698498103040   ERROR:   File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/MSLHttpRequestHandler.py", line 67, in do_GET_

Maybe something with folder creation or python ver.?

Best Regards!

Artur Portella

**Comment by Barborica-Alexandru** [comment] 2018-11-27 01:17
I also am experiencing this issue.

**Comment by caphm** [comment] 2018-11-27 08:32
Duplicate of #550

**Closed by caphm** 2018-11-27 08:32 UTC
