### ISSUE TITLE
[BUG] No watched history

### ISSUE THREAD

**Issue by tonyschuite** [asciidisco/plugin.video.netflix#163] opened 2017-10-02 18:00 UTC
So, I am going to put this here:
I have seen an opened issue where someone comments on the fact that the watched episodes are not sent to Netflix. I have the same problem. I have been using the addon a lot, but no continue watching category showed up. Neither does my watched history contain any of the movies and shows i have watched with the kodi addon. It does work on the web app (annoying thing about netflix is you cannot set the previously watched episodes to watched...)

Sorry if this is a double post, but I just can't seem to find the previous issue.

**Comment by asciidisco** [comment] 2017-10-09 13:52
Wouldn't say it´s a bug, it´s a missing feature, as it doesn't prevent you from watching content using the plugin.

Closing this, as it is a duplicate of https://github.com/asciidisco/plugin.video.netflix/issues/69

I´ve added further documentation about the current results of my ongoing investigations there.

**Closed by asciidisco** 2017-10-09 13:52 UTC
Labels: duplicate
