### ISSUE TITLE
Video starts with black screen and no sound

### ISSUE THREAD

**Issue by n152** [asciidisco/plugin.video.netflix#394] opened 2018-06-10 20:45 UTC
*I'm submitting a ...*
  - [x ] bug report
  - [ ] feature request
  - [ ] support request

## General infomration
I can't watching Netflix videos.
### Prerequisites

* [ x] Are you running the latest version?

### Description

After select any video i have black screen and no sound.

[Description of the bug or feature]

### Steps to Reproduce

1. [First Step] Play any video from Netflix
2. [Second Step] Wait and look

**Expected behavior:** [What you expected to happen]
I want watching video from Netflix.
**Actual behavior:** [What actually happened]
As up.
## Context (Environment)
Android 7.1.2 
Tv Box t95z plus.
### Installation

* [ ] I installed the plugin via zip from the Releases page
* [x ] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [ ] Linux (ARM)
* [ x] Android

#### Additional informatin on the environment

[Descripe your environment a bit more detailed, are you using LibreElec f.e.]

## Debug log

https://m.sendspace.com/file/5u4e4v

## Other information
Earlier on previous version Kodi 18 from April 2018 this addon works correctly. After update Kodi 18 to version from 09.06.2018, i can't watching.

**Comment by peak3d** [comment] 2018-06-11 06:36
pls. use pastebin or something where one can download log without registering

**Comment by n152** [comment] 2018-06-11 06:45
https://pastebin.com/YdBTmSA3
Here :)

**Comment by peak3d** [comment] 2018-06-11 15:48
pls:

- navigate to a stream
- adb logcat -c
- play the stream some seconds
- adb logcat -d | pastebinit

**Comment by n152** [comment] 2018-06-12 14:29
https://pastebin.com/n3NJ1v53
and short movie https://drive.google.com/open?id=1OE6UQbf9gRan6_uNlJGZZu5zu_xc-wD-

**Comment by peak3d** [comment] 2018-06-12 18:48
The issue is "unsufficient output protection" which could be caused by the widevine transfer protocol.
Pls. try branch 394 : https://github.com/asciidisco/plugin.video.netflix/archive/394.zip (install from zip inside kodi)

**Comment by n152** [comment] 2018-06-12 19:04
Not works, i have loading for few seconds and later exit to list of movies.
https://pastebin.com/bcEFsWu8 logcat

**Comment by liberty-developer** [comment] 2018-06-12 19:31
@n152 if you don't trust the support provided hiere (you may know that peak3d is the author of inputstream.adaptive and the DRM part in kodi) we cannot help anymore.
I suggest that we close the issue.

**Comment by n152** [comment] 2018-06-12 19:40
I trust you, but I see that addon works perftect on previous version of Kodi, so maybe this info will be usefull to fix this error :) .

**Comment by peak3d** [comment] 2018-06-12 19:45
@n152 and now? What do you suggest to do?

If you want to solve it your way, I'm fine with it because I don't have to spend hours on your 20$ box issues (which seem to be not existant on other devices),

You could try your luck in stackoverflow or whatever. Don't try kodi trac / forum because you'll be routed to me again.

**Comment by n152** [comment] 2018-06-12 20:13
Ok, if you haven't any more suggestions how can I help you to fix it I want said you thanks for any help and interest with my problem. I hope so it will be ok in future...

**Comment by peak3d** [comment] 2018-06-12 20:33
Could be that the language barrier is the issue here, but we just started investigating.
I read your prev. post that you would like to have other support.

- Deinstall netflix including your userdata (you will be asked during deinstallation)
- Install the version provided above again (the 394.zip file)
- Log in again, and if it fails pls. provide a complete kodi log (debug enabled)

**Comment by n152** [comment] 2018-06-12 20:49
I was trying 3 times play video and no success.

Debug Log https://pastebin.com/jytXP2Ki

**Comment by peak3d** [comment] 2018-06-12 21:08
Last check for tonight:

Pls. restart kodi, and provide the kodi log after trying to play 1(!) stream.

**Comment by n152** [comment] 2018-06-12 21:17
https://pastebin.com/SktdBSYj

**Comment by peak3d** [comment] 2018-06-12 21:35
Ok, unfortunately the old key xchange handling is not worling with your device / ESN so we have to continue investigating with the normal 0.13.8 version.

To prepare your device you should again deinstall the 394.zip version with user_data because there are still keys in userdata folder from old  login procedure.

I'll try to find a widevine L3 device for reproduction. All my L1 devices work without issues.
Could take some days, until then you could report the issue in the german kodinerds.net forum, they normally respond to english, too.

**Comment by caphm** [comment] 2018-09-04 07:55
Inactive

**Closed by caphm** 2018-09-04 07:55 UTC

**Comment by marcosruiz** [comment] 2020-05-13 18:49
This worked for me:
Go into Netflix addon-settings and select inputstream options
Tick "override HDCP Status" and "ignore resolution" - one of that options solved the problem for me. I guess its the resolution thing, as my TV said "not supported signal"
