### ISSUE TITLE
Playing Video stops working

### ISSUE THREAD

**Issue by the-dreamer** [asciidisco/plugin.video.netflix#57] opened 2017-04-14 21:49 UTC
Hi, 

in the noon playing videos from Netflix was working fine. In the evening no video is playing anymore. Full debug log: http://sprunge.us/aPND 

At the end i thing the error:

`23:38:19.763 T:140000025896704   DEBUG: [Netflix] Error getting Manifest: {"signature":"Y1sgmP44hEBk+b9c5bKQ/xGlAswAjGbOJWfc7MgSWB47OSmmaUvuRcJKja8vYWQXsmFkiZ3Tvh+tKaCZsxvYVbtPKgTluSZ76qUt+h1z0sDmjoULQDjfuSshL5GFL0FtfDefRuv67TY0x8y2LF0c1eGSUiEomPyoJ3Ze4qZwCXfBd9fzAg/+mPT+g0i3BiWaVN3HrdEErlgFtLiI/IiJwEreXWyzjJGCvb4qMnmVcZ1aQ+Kew9Ao39dLFNmvOQlFp3ZXGUnpzcSX9lLlrvOjbGNYinus8bQjIXaXor5t4MqdGcetIxpnaiVWxEz0ldR9KoGH/G3CkPH+h+Iw/0xm1Q==","errordata":"eyJpbnRlcm5hbGNvZGUiOjEwNjAxNCwibWVzc2FnZWlkIjoxMTYzMDcxOTAwOTM0NDE2LCJlcnJvcmNvZGUiOjgsImVycm9ybXNnIjoiTWVzc2FnZSBleHBpcmVkIGFuZCBub3QgcmVuZXdhYmxlLiBSZWplY3RlZC4iLCJ0aW1lc3RhbXAiOjE0OTIyMDU4OTl9","entityauthdata":{"scheme":"RSA","authdata":{"identity":"Netflix","pubkeyid":"MSL_TRUSTED_NETWORK_SERVER_KEY"}}}`
is avoiding playing any video anymore. I don't know what is wrong. Playback via webbrowser is still working. Restarting of system didn't help. Other Services (Maxdome/Amazon) are working fine. If you need more info, let me know.

**Comment by trummerjo** [comment] 2017-04-14 22:25
What Plugin Version do you use? Please update to the newest one and test again. Thanks!

**Comment by the-dreamer** [comment] 2017-04-14 23:42
It was not older than a week. I will check newest one.

**Comment by the-dreamer** [comment] 2017-04-15 11:24
Hi, 
reinstall latest master did it working again. i am not sure if reinstall itself fixed it or a new version. as i said, the installed version was only few days old. I will observe it and will inform you again if i occured the same issue again. Thank you so far :-)

**Comment by the-dreamer** [comment] 2017-06-22 20:28
Hi,

possibly not the same root couse, but from today evening it is not possible to play a video anymore: http://sprunge.us/iGaZ

reinstall latest master did not help now. system itself has not been changed since yesterday.

**Comment by maxodoble** [comment] 2017-06-23 10:35
Same for me:

i was able to watch Netflix yesterday, and since today videos aren't starting to play.

Max

**Comment by asciidisco** [comment] 2017-06-23 16:00
Seems that Netflix has changed something regarding the ESN check. We need to figure out what in order to solve this.

**Comment by marcelveldt** [comment] 2017-06-24 18:29
same issue here, netflix refuses to play since a couple of days while it was working great before.

Any quick hints where to look in the code for things that need some adjustments ?

**Comment by trummerjo** [comment] 2017-06-24 18:32
what platform do you all use?

**Comment by asciidisco** [comment] 2017-06-24 18:32
Further investigation by @liberty-developer has shown, that the root cause is, that Netflix now checks if the provided ESN does match the DRM contents. We used a hardcoded ESN in the past, which of course fails now, because this doesn't match the criteria anymore & we don't get a license. @trummerjo is looking into it.

**Comment by marcelveldt** [comment] 2017-06-24 18:51
I'm testing the Kodi agile branch on both Windows x64 and Linux x86-64 (libreelec)

**Comment by joaosagrath** [comment] 2017-06-25 22:24
Mine in Windows 7 Ultimate x64 (In Brasil)

**Comment by asciidisco** [comment] 2017-07-02 19:49
Fixed in 0.11.12

**Closed by asciidisco** 2017-07-02 19:49 UTC
