### ISSUE TITLE
[Library] Allow library .strm files main folder outside plugin data folder

### ISSUE THREAD

**Issue by WilcoVertegaal** [asciidisco/plugin.video.netflix#179] opened 2017-10-10 15:27 UTC
I have a central MySQL database that is shared between multiple Kodi devices. All local media are stored on my NAS. Would it be possible to have the option to save the Netflix media .strm files (needed to add them to the Kodi video library) to a network location, so that all Kodi devices can access them when a user adds them to her library? Right now you are only allowed to choose a folder inside the addon data folder inside a local Kodi user data folder.

**Comment by asciidisco** [comment] 2017-10-10 15:36
I just merged https://github.com/asciidisco/plugin.video.netflix/pull/170 which (please correct me if I´m wrong @hawkeyexp), so it should be included in the next release.

**Comment by hawkeyexp** [comment] 2017-10-10 15:41
It is available since 0.11.25 but has needed a bugfix caused by unicode probs.

it was merged with pr #154

**Comment by WilcoVertegaal** [comment] 2017-10-10 17:05
Hm - I couldn't get outside special://profile - but then as I typed this here as an error report and then toggled back to Kodi, the select folder dialog was showing all top level folders (C:\etc) plus network locations. Weird, but workable.

**Comment by hawkeyexp** [comment] 2017-10-10 17:18
So your problem is solved and we can close the issue ?

**Comment by WilcoVertegaal** [comment] 2017-10-10 17:27
The featur request can be closed, since the intended behaviour already makes it possible - but maybe a bug report would be in place? I can't really reproduce it now that I was able to select the network folder, but I don't know why ... All of a sudden it "just worked" but before that it "just didn't work".

**Comment by asciidisco** [comment] 2017-10-10 18:22
@WilcoVertegaal If it comes up again, then please open another issue.
Thanks for reporting anyway 👍

**Closed by asciidisco** 2017-10-10 18:22 UTC
Labels: enhancement
