### ISSUE TITLE
[Bug Report] OSMC with Kodi 18 alpha not installing all dependencies

### ISSUE THREAD

**Issue by DrCord** [asciidisco/plugin.video.netflix#237] opened 2017-11-20 16:42 UTC
*I'm submitting a ...*
  - [X] bug report
  - [ ] feature request
  - [ ] support request

### Prerequisites

* [X] Are you running the latest version?

### Description

I get this issue on 0.12.7, running OSMC updated to the latest alpha for KODI 18

After installing any version of the plugin I get an error and the dependencies area shows that inputstream.adaptive and script.module.pycryptodome are unavailable. Nothing I have been able to do gets them to install with the rest of the plugin.

I have tried to install multiple versions (after completely uninstalling between tries). I have tried 0.12.7, 0.12.6, 0.12.5, 0.12.4, 0.12.1, 0.12.0 and various 0.11.x versions with no success.

This seems related to this issue: https://github.com/asciidisco/plugin.video.netflix/issues/200 but I am not running windows but instead OSMC.

### Steps to Reproduce

1. Install KODI 18 alpha onto OSMC nightly
2. download this repo
3. put on flash drive
4. install repo into OSMC
5. install netflix addon from repo
6. addon CANNOT install inputstream.adaptive and script.module.pycryptodome

**Expected behavior:** addon install dependencies and works

**Actual behavior:** addon fails to install dependencies inputstream.adaptive and script.module.pycryptodome

### Installation

* [X] I installed the plugin via zip from the Releases page
* [ ] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [X] Linux (ARM) - OSMC running on Raspberry Pi 3
* [ ] Android

#### Additional informatin on the environment

OSMC nightly running on Raspberry Pi 3

## Debug log

No idea how to access the debug log in OSMC, everytime I go to the log it is empty despite getting a notice of error being put into it.

**Comment by Gymnae** [comment] 2017-11-21 09:28
I second that, faced the same problem yesterday.

**Comment by rspierenburg** [comment] 2017-11-22 13:18
I had the same thing happen to me.

**Comment by DrCord** [comment] 2017-11-22 18:00
I tried to start over and only install 0.12.4 and that did not work either, exactly the same message about 2 dependencies not being available.

**Comment by kommagent** [comment] 2017-11-23 15:05
Same here. Tried to install inputstream.adaptive and script.module.pycryptodome manually. Did not help.

**Comment by eagleeyetom** [comment] 2017-11-23 15:47
You need to manually enable inputstream in the add-ons.

**Comment by DrCord** [comment] 2017-11-23 16:00
I've tried that as well as manually installing it and it does not work nor allow you to enable it as far as I can determine. If you want to provide detailed instructions for how to enable it I can try to follow them and let you know if that specifically solves it but I have already attempted enabling the add-on.

**Comment by DrCord** [comment] 2017-11-23 16:28
I've also tried to install various different nightly builds of kodi 18 with no success...

**Comment by Gymnae** [comment] 2017-11-23 16:28
Inputstream appears in my plugins without having installed it manually. Like @DrCord, it cannot be enabled. 
I updated to a new build of OSMC and no change.

**Comment by DrCord** [comment] 2017-11-23 16:37
Gymnae has the exact same behavior I see with multiple version of OSMC nightlies. The plugin shows in my list but cannot be enabled.

**Comment by kommagent** [comment] 2017-11-24 10:31
Plugin is enabled here. But it does not solve the problem.

**Comment by pinoelefante** [comment] 2017-11-24 14:35
have you installed libwidevine library?

**Comment by DrCord** [comment] 2017-11-24 15:59
@kommagent agreed, my list of plugins does show inputstream.adaptive as active but this plugin during install shows inputstream.adaptive as "unavailable"

**Comment by DrCord** [comment] 2017-11-24 16:00
@pinoelefante that does not show as a package that is installable:

sudo apt-get install libwidevine
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package libwidevine

**Comment by pinoelefante** [comment] 2017-11-24 17:07
curl -Ls http://nmacleod.com/public/libreelec/getwidevine.sh | bash

**Comment by DrCord** [comment] 2017-11-24 17:27
@pinoelefante output of that command is:

ERROR: Unable to determine ARCH for this system!
ERROR: Specify ARCH=arm or ARCH=x86_64 if /etc/os-release does not define a suitable ARCH

**Comment by DrCord** [comment] 2017-11-24 17:30
@pinoelefante output of above command:

ERROR: Unable to determine ARCH for this system!
ERROR: Specify ARCH=arm or ARCH=x86_64 if /etc/os-release does not define a suitable ARCH

also tried running command with ARCH:

curl ARCH=arm -Ls http://nmacleod.com/public/libreelec/getwidevine.sh | bash

and got the same output with the above error.

**Comment by rspierenburg** [comment] 2017-11-24 18:01
Check out the post below, you need to revise the getwidevine script.
[https://discourse.osmc.tv/t/how-to-use-netflix-on-osmc-rpi2/11478/18?u=rspierenburg](url)

**Comment by DrCord** [comment] 2017-11-24 18:17
@rspierenburg tyvm for the information, that seemed like it should work, however it did not...both things installed as the guide you linked to said but it did not make any change in the netflix plugin being able to show them as available dependencies.

**Comment by DrCord** [comment] 2017-11-26 01:57
I just went to the latest (17.8-136, 25 Nov 2017) build of Kodi 18, still no luck, same exact issue.

**Comment by DrCord** [comment] 2017-11-27 20:01
If you can tell me a version of OSMC nightly to install that does work for sure then we could proceed down that road. @Gymnae

**Comment by Gymnae** [comment] 2017-11-27 20:04
I wish I could, I couldn't get it to run at all. Thus I hoped that mentioning Sam and his project here would maybe trigger an involvement.

**Comment by rspierenburg** [comment] 2017-11-27 20:05
I'm hearing people saying that it doesn't work with OSMC and HW Accerleration (aka OMXPLAYER).  I can get mine to play with the omxplayer disabled but its really jerky and the audio and video keep getting out of sync.  So if that is the case then, yes the Plugin does technically work for me eventhough it still mentions missing dependencies, but no it is not usable in its current state IMO.

**Comment by samnazarko** [comment] 2017-11-27 20:08
Hi

Thanks for bringing this to my attention.
I don’t keep a close eye on nightlies as much as I should. Users are using Netflix with the latest builds.

If this is a recent regression, can someone point me to a report on the OSMC forum?

Cheers

Sam

**Comment by Gymnae** [comment] 2017-11-27 20:26
Dear Sam, awesome that you post here as well, thank you.
I haven't posted on the forum, but the most up to date discussion regarding netflix and kodi 18 is pertaining the rpi2 and didn't cover the problems described here [1]  but mind you, vero4k has the same issues. 
[1] https://discourse.osmc.tv/t/how-to-use-netflix-on-osmc-rpi2/11478/33

**Comment by samnazarko** [comment] 2017-11-27 20:38
Cheers. I'll take a look at this shortly.

Sam

**Comment by samnazarko** [comment] 2017-11-28 02:07
CC @StormTrooper

**Comment by Gymnae** [comment] 2017-11-29 20:25
Maybe these two snippets from the log help to identify the problem:
```
08:04:46.265 T:3528401904   ERROR: Rename - Error renaming file /home/osmc/.kodi/addons/temp/4f0e9737-256f-46f9-99dd-e6845fc3b62c
08:04:46.265 T:3528401904   ERROR: Failed to move new addon files from '/home/osmc/.kodi/addons/temp/4f0e9737-256f-46f9-99dd-e6845fc3b62c' to '/home/osmc/.kodi/addons/plugin.video.netflix'
08:04:57.264 T:3930252272   ERROR: EXCEPTION: Non-Existent Control 300
08:05:08.442 T:3482317808 WARNING: CPythonInvoker(4): Script invoked without an addon. Adding all addon modules installed to python path as fallback. This behaviour will be removed in future version.
```
`20:52:21.893 T:3885315056 WARNING: CPythonInvoker(1, /usr/share/kodi/addons/script.module.osmcsetting.updates/service.py): the python script "/usr/share/kodi/addons/script.module.osmcsetting.updates/service.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon7xbmcgui12ControlImageE,N14PythonBindings31XBMCAddon_xbmc_Monitor_DirectorE,N9XBMCAddon7xbmcgui6WindowE`

**Comment by Gymnae** [comment] 2017-12-04 21:18
Updated to new nightly and upgrade vero4k to debian stretch - same error

**Comment by samnazarko** [comment] 2017-12-04 21:34
I've pinged GMC about this. We've just been working on preparing nightlies so they work well with Stretch.

**Comment by Gymnae** [comment] 2017-12-04 22:09
Appreciate your support with this. I did not install a package manually with PIP, I just added the repo. libwine is already part of the nightlies, so I thought I did not need to add something manually via pip

**Comment by Gymnae** [comment] 2017-12-05 21:47
I managed to get it to install.
Turns out that a previous installed via the repo created a file at `/home/osmc/.kodi/addons/plugin.video.netflix` instead of a dir. I removed that file and copied the temp folder created by a repo or zip based install over by hand:
`cp -r /home/osmc/.kodi/addons/temp/5b0f783f-b12a-4c5d-8216-fa264f1d4040 /home/osmc/.kodi/addons/plugin.video.netflix`

Now the plugin starts, I can log in, but nothing plays. Thus I added to the related bug https://github.com/asciidisco/plugin.video.netflix/issues/206

**Comment by DrCord** [comment] 2017-12-06 16:55
The file `/home/osmc/.kodi/addons/plugin.video.netflix` does not exist on my box so no way to apply this fix to get things working-ish... @Gymnae

**Comment by Gymnae** [comment] 2017-12-06 19:16
@DrCord Do you have a folder in `/home/osmc/.kodi/addons/temp/ ` which could be the plug-in stuck there? Do you have log messages which could relate to a copy problem?
In regards to your problem of
```
ERROR: Unable to determine ARCH for this system!
ERROR: Specify ARCH=arm or ARCH=x86_64 if /etc/os-release does not define a suitable ARCH
```
run `export ARCH=arm` before running the command

**Comment by tonywagner** [comment] 2017-12-15 02:18
Just encountered a similar issue here, except I am using a 2nd Gen Fire TV stick and the latest Kodi nightly. I manually enabled inputstream.adaptive in the default Kodi repo so the Amazon Video addon works, but those two dependencies still show as "unavailable" so the Netflix addon won't install. (Not a big deal as there is a native Netflix app for me, but I do prefer the Kodi interface at times.)

**Comment by samnazarko** [comment] 2017-12-21 14:51
It should now work on Vero 4K, but you still need to manually install the dependencies at this time I think.

https://github.com/osmc/osmc/commit/7e57403d751ecdd18852cf9614a0015439ed90a7 should be included in a GMC nightly shortly.

**Comment by Gymnae** [comment] 2017-12-21 20:24
Not sure if the nightly with the changes has been deployed, but I ran an update of kodi and tried again, same error:
`0:58:05.552 T:4079677504  NOTICE: VideoPlayer::OpenFile: http://localhost:38286/manifest?id=80028554
20:58:05.553 T:3994022656  NOTICE: Creating InputStream
20:58:08.057 T:3994022656   ERROR: Interface_Filesystem::get_property_values - invalid data (addon='0xee1778d0', file='0xe809ec10')
20:58:10.821 T:3724550912   ERROR: Traceback (most recent call last):
20:58:10.835 T:3724550912   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
20:58:10.836 T:3724550912   ERROR:     self.process_request(request, client_address)
20:58:10.836 T:3724550912   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
20:58:10.836 T:3724550912   ERROR:     self.finish_request(request, client_address)
20:58:10.836 T:3724550912   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
20:58:10.836 T:3724550912   ERROR:     self.RequestHandlerClass(request, client_address, self)
20:58:10.836 T:3724550912   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 652, in __init__
20:58:10.836 T:3724550912   ERROR:     self.handle()
20:58:10.836 T:3724550912   ERROR:   File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
20:58:10.836 T:3724550912   ERROR:     self.handle_one_request()
20:58:10.836 T:3724550912   ERROR:   File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
20:58:10.837 T:3724550912   ERROR:     method()
20:58:10.837 T:3724550912   ERROR:   File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/MSLHttpRequestHandler.py", line 41, in do_POST
20:58:10.837 T:3724550912   ERROR:     self.wfile.write(base64.standard_b64decode(b64license))
20:58:10.837 T:3724550912   ERROR:   File "/usr/lib/python2.7/base64.py", line 96, in standard_b64decode
20:58:10.837 T:3724550912   ERROR:     return b64decode(s)
20:58:10.837 T:3724550912   ERROR:   File "/usr/lib/python2.7/base64.py", line 75, in b64decode
20:58:10.837 T:3724550912   ERROR:     return binascii.a2b_base64(s)
20:58:10.837 T:3724550912   ERROR: TypeError: a2b_base64() argument 1 must be string or buffer, not bool
20:58:10.877 T:3994022656   ERROR: AddOnLog: InputStream Adaptive: License update not successful (no keys)
20:58:10.878 T:3994022656   ERROR: AddOnLog: InputStream Adaptive: Initialize failed (SingleSampleDecrypter)
20:58:10.879 T:3994022656   ERROR: CVideoPlayer::OpenInputStream - error opening [http://localhost:38286/manifest?id=80028554]
20:58:10.880 T:3994022656  NOTICE: CVideoPlayer::OnExit()`

**Comment by StormTrooper** [comment] 2017-12-21 20:27
Not yet. Build is still running. Will be fixed in 17.8-150

**Comment by Gymnae** [comment] 2017-12-21 20:27
Light speed, thank you :)

**Comment by samnazarko** [comment] 2017-12-21 20:41
Keep an eye out for a new build and the instructions. You’ll need to uninstall and reinstall some addons

**Comment by StormTrooper** [comment] 2017-12-22 11:17
Nighty build uploaded which fixes the issue.

https://discourse.osmc.tv/t/testing-kodi-18-leia-builds-for-vero-2-4k/23059/216?u=gmc

If you previously had Netflix addon installed you will need to remove and re-install.  There is something cached within the addon so even with OSMC fixed it still failed for me until I removed/re-added plugin.

**Comment by DrCord** [comment] 2017-12-22 16:22
I still get the exact same inputstream adaptive and pycryptodome unavailable dependencies errors as before this new build. On raspberry pi 3.

**Comment by Gymnae** [comment] 2017-12-22 17:07
Yeah! it works for me! Awesome!
Here are the steps I followed:
```
sudo apt-get update
sudo apt-get dist-upgrade
```
The apt commands might not have been necessary, but for me the GUI update command didn't give me the 150 nightly
To get rid of dependency errors:
```
sudo apt-get install build-essential python-pip
sudo pip install -U setuptools
sudo pip install wheel
sudo pip install pycryptodomex
```
(thanks to Joakim_Sandstorm of OSMC foum)

1. Then I deleted the addon via GUI and made sure no residues were left in addons folder via SSH
2. rebooted
3. Installed addon again via repo
4. Was asked for login, logged in
 
And it works!

**Comment by DrCord** [comment] 2017-12-22 17:24
This seemed to work for me! no playback slowdown as far as I can tell. Thanks so much for your help!!! @Gymnae

**Comment by DrCord** [comment] 2017-12-22 17:34
the expanse won't come up in my search on netflix and I cannot find any other 1080p video to play. 720p video works fine as well as 4k.

**Comment by Gymnae** [comment] 2017-12-22 17:36
Interesting that 4k works fine for you. I also tried some 1080p movies and the problem was the same for all. I just checked my downstream, it's 90mbits - should be fine

**Comment by DrCord** [comment] 2017-12-22 17:37
I'll play some stuff today and report back if I see any issues.

**Comment by Gymnae** [comment] 2017-12-22 17:39
It might be a vero4k problem. Just look at the load on the system when streaming a 720p video. There's no performance left for 1080p or more:
![screen shot 2017-12-22 at 18 38 39](https://user-images.githubusercontent.com/6195487/34307246-62544b9a-e747-11e7-84a4-94a3dedf737f.png)

**Comment by DrCord** [comment] 2017-12-22 17:41
Yeah, I use a Raspberry Pi 3 with a heat sink for the ram and a dual fan as well as I was having overheating issues once I started running older versions of Kodi LEIA with certain videos, not at all since upgrading to the cooling case...

**Comment by samnazarko** [comment] 2017-12-22 17:54
The decoding isn’t hardware accelerated so is indeed being done in software. We might be able to get some more performance out of this

**Comment by DrCord** [comment] 2017-12-27 18:27
I've been noticing that certain high def shows the audio and video get out of sync.

**Comment by samnazarko** [comment] 2017-12-27 19:06
The device is probably struggling

**Comment by mnt-grrrl** [comment] 2017-12-30 23:27
I am running rbp2-mediacenter-osmc                17.8-152    and still having this error. Has anyone gotten this to work on the pi (since it seems to be working on the vero)

**Comment by samnazarko** [comment] 2017-12-30 23:29
The dependency error?

This is just a warning provided that you have installed them -- Kodi is unaware that the dependencies are satisfied

**Comment by mnt-grrrl** [comment] 2017-12-30 23:47
I thought so. I get an error when I try and run the plug in but don't see anything new in /var/log what am I missing. How do I get the plugin to be aware the dependencies are satisfied?

Thank you!

**Comment by samnazarko** [comment] 2017-12-30 23:59
We haven't solved that yet -- but it is not necessary for it to work as explained.

**Comment by asciidisco** [comment] 2018-01-23 12:25
Closing this as it is OS & not plugin related.
Btw.: You´re probably not able to get out more than 720p with software decoding on any ARM powered device atm.

**Closed by asciidisco** 2018-01-23 12:25 UTC
