### ISSUE TITLE
Netflix movie does not start

### ISSUE THREAD

**Issue by peno64** [asciidisco/plugin.video.netflix#407] opened 2018-06-16 22:13 UTC
*I'm submitting a ...*
  - [x] bug report
  - [ ] feature request
  - [ ] support request

### Prerequisites

* [x] Are you running the latest version?
Yes

### Description

When I want to start a movie, the screen flickers for a second but then nothing happens

### Steps to Reproduce

1. Choose any movie from netflix and play it

it should play

after some flickering, nothing has happened

## Context (Environment)
Raspberry PI 3 with libreelect latest nightly build with Kodi 18, with latest nextflix plugin

### Installation

* [x] I installed the plugin via zip from the Releases page
* [ ] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [x] Linux (ARM)
* [ ] Android

#### Additional informatin on the environment

Raspberry PI 3 with libreelect latest nightly build with Kodi 18, with latest nextflix plugin

## Debug log

https://drive.google.com/file/d/13nQgpdRnR7w0Uj6v-BjbKGqP5IV-tGmr/view?usp=sharing

**Comment by dupohuj** [comment] 2018-06-17 10:44
I have that same environment and that same bug after play nothinngs happen

**Comment by peno64** [comment] 2018-06-17 11:44
Just realised that I did not provide a full debug log file. So here is the log with debugging on:
https://drive.google.com/file/d/1gQ1zT9Nu-breDsfi5SDINgUyQq4y041X/view?usp=sharing

**Comment by peno64** [comment] 2018-06-17 13:28
I didn't mention before that I got to kodi 18 by upgrading my previous kodi 17 version. So with all my addons installed, a VPN and so on. This version 17 was perfectly and that was not the reason why I upgraded to 18.
So now I did a fresh install of v17 and then immediately upgraded to v18 without installing any addon except this one to play netflix.
And now this is working. So it must be because of previous installed addons.
Is that also for you the case dupohuj?

But it seems that there is no buffering of the stream at all with result that it does not play very well. In fact it is not usable as such.
I did configure caching via an advancedsettings.xml file but is looks like it is not used. This works very well for me in kodi 17 with the streaming addons like coventant.
Is that not used by this netflix addon?
Is there another way to configure caching or buffering with this addon?

**Comment by liberty-developer** [comment] 2018-06-17 13:39
@peno64 you should look for the root cause of your buffering issues. Most users don't have any issues (like me). Netflix addon uses the kodi internal 8 seconds buffer, if your network is fine, you should live without issues.

**Comment by liberty-developer** [comment] 2018-06-17 13:48
@peno64 caching is not netflix addon related,(its inputstream.adaptive / kodi), can we close this issue post?

**Comment by dupohuj** [comment] 2018-06-17 16:05
I not upgrade to kodi 18
I just  install kodi 18 leia i will try reinstall maybe new pre release kodi 18 is show up will check it

**Comment by iShyboy** [comment] 2018-06-19 03:39
fresh install kodi 18 on Android and Windows 7 fresh install. Video flick and don't play. Dunno what's wrong.

**Comment by liberty-developer** [comment] 2018-06-19 10:38
@iShyboy no log, no issue.

**Closed** 2018-09-04 07:55 UTC
