### ISSUE TITLE
No hd reso on some US programms 

### ISSUE THREAD

**Issue by devil-strike** [asciidisco/plugin.video.netflix#184] opened 2017-10-11 18:38 UTC
Soms weird problem here with Netflix nl, some programs wont playback in 720p/1080p but in 480p only.

Strange part is that the program is in hd on pc aswel on smarttv but on libreelec Milhouse 9 build it only show the contect in sd, think 90% of the series are fine like all nf original series and others but some only shows in 480p like designated surv. and all DC series.

Tested some other settings like max bitrate override hdcp etc but notting seems to work for the above series.

Logfile:
http://sprunge.us/ifYc

Sysinfo:
Kodi (18.0-ALPHA1 Git:d00d76f). Platform: Linux x86 64-bit, LibreELEC (Milhouse): devel-20171010210712-#1010-g87d8234
Intel(R) Celeron CPU J3355

**Comment by asciidisco** [comment] 2017-10-12 09:54
The problem is, that Linux isn't "officially supported" by Netflix.
The problems here are not with Netflix directly, but with the content owners, that don't allow Netflix to send out their content in HD quality on "these open Linux devices, that don't provider a proper DRM"...

We have to comply with that, also out of a purely technical reason, that Netflix matches the user agent with a system specific ESN they create at the initial request (and that we have to send along with the request that returns the available video streams to us). That could be easily tricked, but the catch is, that the binary widevine decrypter/decoder library also knows wich system it´s running on 
and checks if the stream it received matches that as well....

There´s a reddit thread, that at least describes the issues mentioned by you: https://www.reddit.com/r/netflix/comments/2wb2f1/is_anyone_able_to_watch_netflix_in_hd_in/

Just to make sure, that this is not a plugin issue, you could set the stream selection to manual in the inputstream.adaptive settings (which will first end up playing all content in the lowest res available) & while the episode is playing, you can switch to the video setting & get a list of all streams offered for this video. If there is now HD one, then it´s probably 99.9% the reason I mentioned above.

**Comment by devil-strike** [comment] 2017-10-12 12:09
Ah ok didn't know that, because all other shows like new star trek discovery works fine in 1080, but thanks for the explanation :)

About manual selection only sd is indeed show, not hd reso,  something 848x and lower only.

**Comment by asciidisco** [comment] 2017-10-12 17:16
Sorry that I´m not able to provide a more satisfying answer...
I hope it´s okay to close this then?!

**Closed by asciidisco** 2017-10-12 17:16 UTC
Labels: question

**Comment by devil-strike** [comment] 2017-10-12 18:29
Yes no problem is nothing you can do about it.

Thanks for the explanation :)
