### ISSUE TITLE
Content not fully grabbed by addon

### ISSUE THREAD

**Issue by hawkeyexp** [asciidisco/plugin.video.netflix#113] opened 2017-09-03 17:28 UTC
It seems in compare between the webinterface and the content listed in the addon not all movies are visible in the addon.

**Comment by asciidisco** [comment] 2017-09-04 09:58
Duplicate of https://github.com/asciidisco/plugin.video.netflix/issues/42

**Closed by asciidisco** 2017-09-04 09:58 UTC
