### ISSUE TITLE
Greek subtitles?

### ISSUE THREAD

**Issue by iliaspavlou** [asciidisco/plugin.video.netflix#281] opened 2018-01-29 07:51 UTC
*I'm submitting a ...*
  - [ ] bug report
  - [x ] feature request
  - [ ] support request

* [x ] Are you running the latest version?

I'm using an RPi 3 with original PSU, libreelec Alpha from Mid Jan '18. The plugin works most of the time well. The main issues are cache issues that guide the movie to stop playing, although i have a VDSL line. But this might not be an issue of the plugin. I need to make more tests because i'm running it via PowerLine adapters. What is important for me is the Greek Subtitles. The plugin pulls only the English and Turkish subs. The same happens to my older Samsung smartTV with an outdated version of Netflix and this is the reason i decided to try on your plugin with RPi3. On my iPad the greek subs are selectable and playing without issues. Is it possible to get Greek subs with your plugin?

Regards,

Elies

**Comment by irgendwie** [comment] 2018-01-29 10:09
Duplicate of #95

**Closed** 2018-01-31 09:27 UTC
Labels: duplicate
