### ISSUE TITLE
Netflix stopped working for me. :(

### ISSUE THREAD

**Issue by ymca11** [asciidisco/plugin.video.netflix#216] opened 2017-10-27 13:48 UTC
*I'm submitting a ...*
  - [ ] bug report

## General information

Was working but now stopped working for some reason.

### Prerequisites

running the latest version

### Description

[Description of the bug or feature]
When going into a series I get this message "Netflix error, check error log for more information"

### Installation

* [ ] I installed the plugin via zip from the Releases page
* [ ] I´m using the Netflix Repo

### Operating System
* [ ] Windows (x64)

## Debug log

https://pastebin.com/GTettGVX

**Comment by asciidisco** [comment] 2017-10-27 15:08
Duplicate of https://github.com/asciidisco/plugin.video.netflix/issues/215

**Closed by asciidisco** 2017-10-27 15:08 UTC
Labels: duplicate
