### ISSUE TITLE
[ESN] Plackback Failed message in all content.

### ISSUE THREAD

**Issue by blackman91** [asciidisco/plugin.video.netflix#249] opened 2017-12-06 03:54 UTC
I am using the latest kodi 18 nightly and the latest version of this addon but everytime I try to play something on Netflix this message appears:
![screenshot_20171205-205050](https://user-images.githubusercontent.com/6578180/33643719-96a9b612-da06-11e7-976a-4d8f75adabec.png)

Here is the log:
[kodi.log](https://github.com/asciidisco/plugin.video.netflix/files/1533829/kodi.log)

Any help please?

**Comment by blackman91** [comment] 2017-12-06 07:24
I think I found the relevant part of the log:

DEBUG: AddOnLog: InputStream Adaptive: Download http://localhost:52481/manifest?id=80108801 finished
20:04:02.288 T:18446744072002447664    INFO: AddOnLog: InputStream Adaptive: Successfully parsed .mpd file. #Streams: 16 Download speed: 0.0000 Bytes/s
20:04:02.290 T:18446744072002447664   DEBUG: CAddonSettings[inputstream.adaptive]: loading setting definitions
20:04:02.290 T:18446744072002447664   DEBUG: CAddonSettings[inputstream.adaptive]: trying to load setting definitions from old format...
20:04:02.293 T:18446744072002447664   DEBUG: CAddonSettings[inputstream.adaptive]: loading setting definitions
20:04:02.294 T:18446744072002447664   DEBUG: CAddonSettings[inputstream.adaptive]: trying to load setting definitions from old format...
20:04:02.296 T:18446744072002447664   DEBUG: AddOnLog: InputStream Adaptive: Entering encryption section
20:04:02.305 T:18446744072002447664   DEBUG: AddOnLog: InputStream Adaptive: Successful instanciated media_drm: 0xbc7efdd0, deviceid: , security-level:
20:04:02.305 T:18446744072002447664   ERROR: AddOnLog: InputStream Adaptive: Unable to install Event Listener (-10003)
20:04:02.306 T:18446744072002447664   ERROR: AddOnLog: InputStream Adaptive: OpenDRMSystem failed
20:04:02.306 T:18446744072002447664   DEBUG: AddOnLog: InputStream Adaptive: Session::~Session()
20:04:02.308 T:18446744072002447664   ERROR: CVideoPlayer::OpenInputStream - error opening [http://localhost:52481/manifest?id=80108801]
20:04:02.309 T:18446744072002447664  NOTICE: CVideoPlayer::OnExit()
20:04:02.309 T:18446744072002447664   DEBUG: AddOnLog: InputStream Adaptive: Close()
20:04:02.310 T:18446744072002447664   DEBUG: SECTION:UnloadDll(/data/app/org.xbmc.kodi-1/lib/arm/libinputstream.adaptive.so)
20:04:02.312 T:18446744072002447664    INFO: ADDON: Dll Destroyed - InputStream Adaptive
20:04:02.313 T:18446744072002447664   DEBUG: Thread VideoPlayer 18446744072002447664 terminating
20:04:02.328 T:18446744072040032560   DEBUG: ------ Window Init (DialogConfirm.xml) ------

Any ideas?

**Comment by Wheemer** [comment] 2017-12-08 17:51
You don't have everything setup properly, this is not a bug. You need to copy over the dll, follow the instruction again.

**Comment by blackman91** [comment] 2017-12-09 00:10
What dll exactly? I am using this on Android 6, I downloaded the kodi nightly, installed the netflix addon via the repository and enabled Inputstream.adaptive, what else am i missing?

**Comment by ShlomiABA** [comment] 2017-12-09 01:28
You have to find Kodi folder that place in %APPDATA%. (Just paste this path in file explorer search line). 
Then You got to create a new folder that calls cdm. Then Download the Libwidevine files in this link:

https://hg.mozilla.org/mozilla-central/raw-file/31465a03c03d1eec31cd4dd5d6b803724dcb29cd/toolkit/content/gmp-sources/widevinecdm.json

Choose the file for your operating system (windows,mac or linux) and then unzip it and move the file of this to your cdm folder that you created in Kodi folder. Then open Kodi again and it shut work well.

**Comment by blackman91** [comment] 2017-12-09 02:46
Yep I am using Android 6, any idea why playback always fails based on that log?

**Comment by Sjaakafhaak** [comment] 2017-12-10 18:27
I have the same issue running Kodi 18 Milhouse LibreElec on a Xstreamer Ultra 2.

**Comment by blackman91** [comment] 2017-12-14 19:25
Any solutions guys? I am using an Android Box with Android 6.

**Comment by blackman91** [comment] 2017-12-18 01:10
I checked my Netflix add on installation and found this: 
https://i.imgur.com/JRigD5e.png

Inputstream.adaptive is already enabled any ideas?

**Comment by anscarlett** [comment] 2018-01-21 16:08
Just tried this plugin, I'm getting the same issue. Android TV on Sony Bravia. Any ideas?

**Comment by asciidisco** [comment] 2018-01-22 15:50
This is probably due to the fact that the ESN calculation for Android is rather glitchy at the moment, one thing you could do to help get this fixed, is to post the ESN that is displayed in the Netlfix app on your device & the one that is stored in the settings of the plugin in Kodi.

Once you posted it (important to improve the calculation for everyone), you could also try to alter the ESN in your configuration to be the same as the one in your Netflix app & restart Kodi.
It might work then.

**Comment by asciidisco** [comment] 2018-01-23 15:01
Closing this in favour of: https://github.com/asciidisco/plugin.video.netflix/issues/155

**Closed by asciidisco** 2018-01-23 15:01 UTC
Labels: android, bug, possible duplicate

**Comment by blackman91** [comment] 2018-01-28 01:55
Tried to match the ESN like you said and restarted Kodi but I still get the same error, here are my screenshots:

![screenshot_20180127-191934](https://user-images.githubusercontent.com/6578180/35478173-916317de-039b-11e8-9771-f09576bae47e.png)
![screenshot_20180127-192659](https://user-images.githubusercontent.com/6578180/35478174-931ebde4-039b-11e8-9a8e-1ccb18a164f4.png)


Also why was this closed? It is not sure it is the same bug as the other issue.
