### ISSUE TITLE
Only 40 movies/tvshows on each category

### ISSUE THREAD

**Issue by ntilagoa** [asciidisco/plugin.video.netflix#217] opened 2017-10-27 14:05 UTC
*I'm submitting a ...*
  - [ ] bug report
  - [ ] feature request
  - [X ] support request

## General infomration

I only get 40 movies or tvshows on each genre that i browse.
Also today when try to browse a tvshow it returns error.
Movies work ok. Also tv shows that i already have on my library via emby/kodi work ok.
Thanks

### Prerequisites

* [ ] Are you running the latest version?

### Description

[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Installation

* [ ] I installed the plugin via zip from the Releases page
* [ ] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [ ] Linux (ARM)
* [ ] Android

#### Additional informatin on the environment

[Descripe your environment a bit more detailed, are you using LibreElec f.e.]

## Debug log

[Please include a link to your debug log (use something like [http://sprunge.us/](http://sprunge.us/)) or similar, please do not paste]

## Other information

[e.g. detailed explanation, related issues, suggestions how to fix, links for us to have context, etc.]

### Screenshots

[Please add a screenshot if that helps understanding your problem]

[You can erase any parts of this template not applicable to your Issue.]

**Comment by im85288** [comment] 2017-10-27 14:17
No debug log, no mention of what OS you are using, no mention of what version you are using. How can you expect anyone to help with the lack of information supplied? Always supply as much information as you can, it takes some time but remember it takes the developers a lot of time so sparing a few more minutes of your own time is the least that can be done.

Also don't forget to check out other reported issues....2 have been created today with regards not being able to browse episodes...so sounds like a duplicate. But the mention of only 40 per category could be unique so it would be helpful to state how many you see in Netflix ideally with a screenshot

**Comment by ntilagoa** [comment] 2017-10-27 14:50
Hello
Sorry for the lack of information.
I am running the plugin on the latest nightly of Kodi 18, on a Nvidia shield tv(1st gen).
My library is working with emby/kodi with the emby server running on a windows server machine.
I have added some tvshows and some movies to my library (all play ok through the library), only when browsing the plugin I am not able to browse the episodes.
Concerning the 40 entries per category I try later to send screenshot or more info, because now I'm at work.
Thanks for your help.

**Comment by asciidisco** [comment] 2017-10-27 15:07
Duplicate of https://github.com/asciidisco/plugin.video.netflix/issues/215

**Closed by asciidisco** 2017-10-27 15:07 UTC
Labels: duplicate
