### ISSUE TITLE
[MSL] Cryptodomex issues

### ISSUE THREAD

**Issue by lehabibi** [asciidisco/plugin.video.netflix#85] opened 2017-08-02 09:34 UTC
https://pastebin.com/QhHSDWgF

Can't seem to find an answer to this problem. Tried 32/64bit 2.7.2-2.7.13 Python, still cannot get it to work for the life of me. It doesn't even launch, just instantly errors out.

**Comment by SimonDeRidder** [comment] 2017-08-03 17:37
I'm also getting errors related to Cryptodome, and installing pycryptodome through pip doesn't seem to resolve it.
[https://pastebin.com/E2Kb1ygY](url)

**Comment by allcolor** [comment] 2017-08-04 13:07
Hi, I have the same issue.
Error Contents: Cannot load native module 'Cryptodome.Cipher._raw_ecb'

**Comment by asciidisco** [comment] 2017-08-04 18:12
We once had an issue similar to this: https://github.com/asciidisco/plugin.video.netflix/issues/36
@trummerjo You have initially created this, any further thoughts?

**Comment by allcolor** [comment] 2017-08-10 14:44
Hi again,

by using the Cryptodome distribution found here https://github.com/mchristopher/PokemonGo-DesktopMap/tree/master/app/pylibs/win32/Cryptodome and putting it inside "DRIVE:\Kodi\addons\script.module.pycryptodome\lib\Cryptodome" I do no longer have the error (But using the one which you can retrieve with pip install does not work.) and I can launch the plugin... 

So I can browse the netflix library... but cannot play anything, now kodi complains with "Playback error, missing inputstream addon"... Inputstream adaptative is I think included with kodi 18, and I did install widevinecdm.dll and symlink ssd_wv.dll into %APPDATA%/Roaming/Kodi/cdm.

The log is not helpful, it contains: ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.netflix/?action=play_video&infoLabels....

Any hint ?

Thank you

**Comment by allcolor** [comment] 2017-08-10 15:15
Well... I'm not so sure it's the fact that I changed Cryptodome from the package above that made it works....

It seems it's linked with the nightly build of kodi instead... With the nightly of 02/08 it works... (till the missing inputstream) but not with the one of 10/08.

**Comment by lehabibi** [comment] 2017-08-10 15:52
doesnt work no matter what version i use of what. Kodi, cryptodome or whatever, cant get past "**OSError: Cannot load native module 'Cryptodome.Cipher._raw_ecb**'"

**Comment by asciidisco** [comment] 2017-08-10 19:37
We need more information to track this down.
@allcolor @lehabibi @SimonDeRidder Could you please give me the following data from your systems:

- Kodi version (the exact nightly you´re using - date)
- Inputstream.adaptive version
- Your OS and OS version
- A full Kodi debug log

**Comment by allcolor** [comment] 2017-08-11 12:38
Ok.
I'm on windows 10 64 bits... with the latest patch installed.

with KodiSetup-20170702-32eca2db44-master-x86.exe in 32bits *without having to add the scripts Kodi\addons\script.module.pycryptodome\lib\Cryptodome as it is present after installing Kodi to the contrary of any other nightly I have tried*.

I've installed the repo and installed the plugin and then run it, it connects correctly to netflix, I can browse my library... but when trying to launch a video, I have "Playback error, missing inputstream addon".

**Comment by allcolor** [comment] 2017-08-11 12:39
[kodi.txt](https://github.com/asciidisco/plugin.video.netflix/files/1217830/kodi.txt)

**Comment by asciidisco** [comment] 2017-08-11 12:44
@allcolor Can you check if the inputstream.adaptive plugin is enabled in your plugin browser?

**Comment by allcolor** [comment] 2017-08-11 12:45
All nightly I've tried in x64 (from 30/07, 03/08, 09/08) are missing the lib/Cryptodome... if I take it from a python 2.7 x64 with pip and add it in Kodi\addons\script.module.pycryptodome\lib\Cryptodome I have then the error **"OSError: Cannot load native module 'Cryptodome.Cipher._raw_ecb'"**.

For win32, the nightly of 02/08 works (**till missing inputstream addon**)  if I take it from a python 2.7 a x86 Cryptodome with pip... contrary to the nightly of 02/07, I have to add the Cryptodome lib, because the kodi nightly does not provide it. With the x86 nightly of the 09/08, i have  **"OSError: Cannot load native module 'Cryptodome.Cipher._raw_ecb'"**..

What version of kodi nightly does work till playing... I don't know ;)

**Comment by allcolor** [comment] 2017-08-11 12:48
Ok it was not enabled... but no luck, it still does not work. But no error message now...

Simply not playing.

[kodi.txt](https://github.com/asciidisco/plugin.video.netflix/files/1217848/kodi.txt)

**Comment by allcolor** [comment] 2017-08-11 12:49
If I reclick on launch, I have an error message and in the log I have:
14:49:02.619 T:244652   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.netflix/?action=play_video&infoLabels=%7B%27plot%27%3A+u%22Effray%5Cxe9+par+le+comportement+des+habitants+du+village%2C+John+tente+en+vain+de+s%5Cu2019enfuir%2C+avant+de+faire+la+d%5Cxe9couverte+d%27un+passage+secret+dans+la+maison+de+sa+tante.%22%2C+%27episode%27%3A+2%2C+%27rating%27%3A+0%2C+%27mpaa%27%3A+u%27%27%2C+%27tvshowtitle%27%3A+%27Hero+Corp%27%2C+%27title%27%3A+u%27Le+Test%27%2C+%27mediatype%27%3A+u%27episode%27%2C+%27season%27%3A+1%2C+%27duration%27%3A+1478%2C+%27year%27%3A+2008%2C+%27genre%27%3A+u%27S%5Cxe9ries+fran%5Cxe7aises%27%7D&video_id=80136296&start_offset=1473]
14:49:02.621 T:244652  NOTICE: CVideoPlayer::CloseFile()
14:49:02.621 T:244652  NOTICE: VideoPlayer: waiting for threads to exit
14:49:02.621 T:244652  NOTICE: VideoPlayer: finished waiting
14:49:02.621 T:244652  NOTICE: CVideoPlayer::CloseFile()
14:49:02.621 T:244652  NOTICE: VideoPlayer: waiting for threads to exit
14:49:02.621 T:244652  NOTICE: VideoPlayer: finished waiting
14:49:05.085 T:244652 WARNING: CGUIWindowManager - CGUIWindowManager::OnAction - ignoring action 107, because topmost modal dialog closing animation is running

**Comment by allcolor** [comment] 2017-08-11 12:52
ERROR: AddOnLog: InputStream Adaptive: Unable to handle decryption. Unsupported!

I have this... I have a copied the "widevinecdm.dll" from my chrome install and make the symlink for ssd_wv.dll in %APPDATA%/kodi/cdm...

I'll try with another widevinecdm.dll

**Comment by asciidisco** [comment] 2017-08-11 12:54
@allcolor You don't (and shouldn't) copy/symlink the `ssd_wv.dll`
This is now integrated in Kodi itself. It will only with the one that is bundled with the Kodi Nightly.

This is true for all future Kodi 18 versions. Basically all you need is the widevine.dll.

**Comment by allcolor** [comment] 2017-08-11 12:57
Well I've tried with the one here:
https://www.opendll.com/index.php?file-download=widevinecdm.dll&arch=32bit&version=#
And I got:
14:56:11.722 T:239828   ERROR: AddOnLog: InputStream Adaptive: Unable to handle decryption. Unsupported!
14:56:11.722 T:239828   ERROR: CVideoPlayer::OpenInputStream - error opening [http://localhost:50349/manifest?id=80136295]

**Comment by allcolor** [comment] 2017-08-11 12:57
(I've removed the symlink).

**Comment by asciidisco** [comment] 2017-08-11 12:59
@allcolor Try downloading the latest chrome from here: http://www.slimjet.com/chrome/google-chrome-old-version.php & unzip it.

There should be a proper DLL in this folder: `Chrome-bin\<Chrome Version Number>\WidevineCdm\_platform_specific\win_x86\`

**Comment by allcolor** [comment] 2017-08-11 13:09
So I've taken the 59.0.3071.86 from the site above, copied the DLL into %APPDATA%/Kodi/cdm... still no luck.

15:08:30.436 T:250592  NOTICE: Creating InputStream
15:08:31.083 T:250592   ERROR: AddOnLog: InputStream Adaptive: Unable to handle decryption. Unsupported!
15:08:31.083 T:250592   ERROR: CVideoPlayer::OpenInputStream - error opening [http://localhost:55515/manifest?id=80136295]

**Comment by allcolor** [comment] 2017-08-11 13:10
I've also tested with the latest google chrome canary, same thing.

**Comment by allcolor** [comment] 2017-08-11 13:46
\o/ Success I've made it work...

I've installed the kodi nightly from 09/08 on top of the former of the 02/07 and now it works... And the lib/Cryptodome is present... don't know why when I did install it before, it was missing (or maybe it was missing only on the x64 ? or maybe the antivirus trashed it ?).

Anyway, I can play netflix now... I used the winedevinecdm from the google canary setup... (and also copied the cdmadapter.dll).

**Comment by asciidisco** [comment] 2017-08-11 15:53
@allcolor Great \o/
Now that you've written 02/07, a bell rang that something in the early July 32bit versions was broken...

It's always good to give the latest version a try.

So, 1 out if 3 works. Lets tackle the others :D

**Comment by sumanex** [comment] 2017-08-11 16:01
I was also struggling for a few days with this issue. I downloaded the 32 bits nightly from 9th august and just had to copy the w'vine cdm and cdmadapter from latest chrome running in my computer to the cdm folder to get it working.nice. thanks for solving it.

**Comment by asciidisco** [comment] 2017-08-15 09:27
For reference, duplicate issue: https://github.com/asciidisco/plugin.video.netflix/issues/94

**Comment by WilcoVertegaal** [comment] 2017-08-23 06:50
I'm still experiencing the issue with Kodi Nightly Build from August 22. I'm on Windows 10 using 64 bit Kodi. The log file says this:

08:06:33.159 T:13580   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named Cryptodome.PublicKey
                                            Traceback (most recent call last):
                                              File "C:\Users\GroundBreaking\AppData\Roaming\Kodi\addons\plugin.video.netflix\service.py", line 10, in <module>
                                                from resources.lib.KodiHelper import KodiHelper
                                              File "C:\Users\GroundBreaking\AppData\Roaming\Kodi\addons\plugin.video.netflix\resources\lib\KodiHelper.py", line 11, in <module>
                                                from MSL import MSL
                                              File "C:\Users\GroundBreaking\AppData\Roaming\Kodi\addons\plugin.video.netflix\resources\lib\MSL.py", line 19, in <module>
                                                from Cryptodome.PublicKey import RSA
                                            ImportError: No module named Cryptodome.PublicKey
                                            -->End of Python script error report<--

**Comment by allcolor** [comment] 2017-08-23 07:54
Use the 32bits version of the 09/08, it works... there is obviously a problem with the cryptodomex lib... even if you take it with pip, it doesn't work on those broken nightly... the problem is with kodi not the netflix plugin... so if you want to use it, use the 09/08 32 bits version.

**Comment by WilcoVertegaal** [comment] 2017-08-23 12:04
OK so instead of reporting it here, it should really be reported to the Kodi developers?

**Comment by asciidisco** [comment] 2017-08-23 12:05
Most probably, yes. But lets leave the issue open here as well, so people with the problem have a goto source & see that it´s not a problem on their system.

**Comment by domtik** [comment] 2017-09-03 14:19
Thank you guys for all the guidelines. I've made a step by step Netflix installation tutorial (in French) with direct download links for people who use Kodi with Windows.
https://domtik.com/index.php/2017/09/03/addon-netflix-kodi/

**Comment by cbasstn** [comment] 2017-09-23 15:09
Thank you for the guide @domtik , too bad that working Nightly build is no longer available now. Does anybody know of another version with working pycryptodome?

**Comment by kat953162** [comment] 2017-09-25 16:39
Instead, can someone just host the working copy on a cloud sharing service and link to it?

Just as a temporary solution of course.

**Comment by centralseven** [comment] 2017-09-27 17:05
I found a mirror with older nightlies.
http://ftp.igh.cnrs.fr/pub/xbmc/xbmc/nightlies/windows/win32/master/

**Comment by cbasstn** [comment] 2017-09-27 17:35
Awesome thanks a lot @centralseven !

**Comment by ymca11** [comment] 2017-09-28 10:26
I didn't know it was that complicated.

 trummerjo told me to install Cryptodome.
I was trying to download Cryptodome from the link allcolor posted.
"https://github.com/mchristopher/PokemonGo-DesktopMap/tree/master/app/pylibs/win32/Cryptodome"

I didn't found a way to download the Cryptodome there, so I have searched the net for another place and found this. Is this good?

https://pypi.python.org/packages/e2/2f/cba044f7558649da3525eb66104e25e038f6e2f2b88c3037e561e93c7a33/pycryptodomex-3.4.2-cp35-cp35m-win_amd64.whl#md5=c90bcbd62c2a1e31346cd2adcdd3af65

Here is my log if needed.
https://pastebin.com/1UH890Hx

**Comment by allcolor** [comment] 2017-09-28 10:32
Just install this nightly http://ftp.igh.cnrs.fr/pub/xbmc/xbmc/nightlies/windows/win32/master/KodiSetup-20170809-67137d6348-master-x86.exe and it will work.

**Comment by kat953162** [comment] 2017-09-28 10:32
Cryptodome should be installed with Kodi I believe.

Try this build:  http://ftp.igh.cnrs.fr/pub/xbmc/xbmc/nightlies/windows/win32/master/KodiSetup-20170809-67137d6348-master-x86.exe

Thank you so much @centralseven

**Comment by kat953162** [comment] 2017-09-28 10:33
@allcolor you beat me by seconds!

**Comment by allcolor** [comment] 2017-09-28 11:02
Yes, you must enabled the plugin inpustream adaptive, it is off by default.

If that doesn't solve it, then attach the log.

**Comment by kat953162** [comment] 2017-09-28 11:05
That was enabled already.

Either way, I JUST managed to fix it by manually installing the addon using the latest master.

Next I'm gonna test the video streaming.

**Comment by valerir01** [comment] 2017-09-28 11:24
is there any way to get netflix plugin workin android tv box (amlogic 905w) please? Installed Kodi master nightly from August 9th. Enabled inputstream adaptive. Created directory cdm under /.kodi and have put there libwidevinecdm.so. Installed Netflix plugin. When I look into plugin settings, then under dependencies I still see pycryptodome unavailable. Have no idea where to look further.

**Comment by ymca11** [comment] 2017-09-28 12:12
Thanks allcolor, but I'm using a 64bit Kodi because I have problems watching files that are coded in 265 with the 32bit.
I'm using this version
"18.0-ALPHA1 Git:20170811-69f283b"
Is it ok for that?

I also saw here that you said "inpustream" should be enabled. 
Do I need to install this plugin from somewhere?

**Comment by allcolor** [comment] 2017-09-28 12:52
The plugin is installed but not enabled, just go in the extension configuration and enable it... As for a 64bits version, I did not found any that has worked for me...

**Comment by pinoelefante** [comment] 2017-09-28 13:50
I am using Kodi 18 x86 (9 September 2017) and is working. Haven't update yet to try if still works

**Comment by domtik** [comment] 2017-09-29 12:34
Hello, for those who are looking for the working Nightly build you can download it in this post: 
https://domtik.com/index.php/2017/09/03/addon-netflix-kodi/

**Comment by walinsky** [comment] 2017-09-29 18:55
On ubuntu plugins need to be installed explicitly with apt-get.
I managed to get netflix running perfectly on a nightly kodi build (installed latest as of today).
I had to pip install pycryptodomex by hand; as the netflix plugin didn't get to pulling it as a dependency.
After that it took me quite a while to figure out I had to sudo apt-get install kodi-inputstream-adaptive.
After that it was plain sailing.

**Comment by Johunn** [comment] 2017-10-04 21:26
Hello I am using the Netflix addon with kodi 18 on my android box (nvidia shield), it worked a week and now suddenly I have an error message when I launch Netflix... I don't know where I can find the description of this error message, and I see in the requested addon "script.module.pycryptodome" is missing. I tried to install several versions of kodi 18 and uninstall / reinstall the addon but the problem is always there. Someone could help me please ?

**Comment by asciidisco** [comment] 2017-10-09 20:50
Cryptodomeex should be included in the current Nightlies for x64 devices.
If one of you could test it & give some feedback, it would be much appreciated.

**Comment by ymca11** [comment] 2017-10-09 22:14
asciidisco, how can I be sure before I install it that it has the "Cryptodomeex"?
http://mirrors.kodi.tv/nightlies/windows/win64/master/KodiSetup-20171007-bedc63fc8a-master-x64.exe

**Comment by Johunn** [comment] 2017-10-09 22:29
I have desactivated and reactivated the addon and Netflix works now... I don't know why but I must do that once a day to make him work correctly.
I have the last nightlies x64 for Android but look the screen :
![screenshot_20171010-002750](https://user-images.githubusercontent.com/32527234/31361116-f785d6a0-ad51-11e7-80f7-5df93932aab0.png)

**Comment by WilcoVertegaal** [comment] 2017-10-10 06:08
Great! Last nightly for x64 seems to include cryptodomex, and the add-on seems to work fine.

**Comment by asciidisco** [comment] 2017-10-10 07:38
@ymca11 Don't know if there´s a way, besides checking the output of the build server.
@Johunn I have no idea  why that´s the case, but I´m also not an Android user.
Don't think you can update it from within itself.

**Comment by ymca11** [comment] 2017-10-10 12:17
Now I can see my netflix account but not play.
I think it will work after I add a file.
Here domtik made a french help:
https://domtik.com/index.php/2017/09/03/addon-netflix-kodi/

I have seen that in the help there is a 32bit chrome and not 64.
Is there a 64bit version?

**Comment by asciidisco** [comment] 2017-10-10 12:30
@ymca11 It´s not related to Cryptodome then (future remark, always include a debug.log).
I think you´re talking about widevine, there is a link in the readme of the repo with download links for all platforms (excluding ARM): https://hg.mozilla.org/mozilla-central/raw-file/31465a03c03d1eec31cd4dd5d6b803724dcb29cd/toolkit/content/gmp-sources/widevinecdm.json

**Comment by asciidisco** [comment] 2017-10-10 12:47
I would appreciate if anything in regards to this would find its way into the Kodi Bugtracker (https://trac.kodi.tv).
I´ve looked for any reports there & no one has reported issues.

Here are some existing issues that are all related to the initial implementation, so if someone opens a bug in the tracker, the corresponding one should be linked: https://trac.kodi.tv/search?q=cryptodome

Closing this, as this is not related to the plugin, but to Kodi itself.

**Closed by asciidisco** 2017-10-10 12:47 UTC
Labels: question

**Comment by ymca11** [comment] 2017-10-10 15:55
Thanks asciidisco. :)
That's exactly what I've needed.
https://redirector.gvt1.com/edgedl/widevine-cdm/970-win-x64.zip
And remembering where to put it :) "\AppData\Roaming\Kodi\cdm"
Now it's working 8)

**Comment by theboy181** [comment] 2017-12-18 05:05
I’m using Ubuntu and I have logged on but I get a playback error when I try to load any videos. Can anyone please point me in the right direction to get it working?
