### ISSUE TITLE
[Enhancement] Lists only have 27 entries

### ISSUE THREAD

**Issue by tonyschuite** [asciidisco/plugin.video.netflix#106] opened 2017-08-27 21:22 UTC
I noticed the lists show a lot of Series, but only a few movies.
Then I noticed that all lists have exactly 27 entries. Should be a lot more according to the netflix site listings.

**Comment by asciidisco** [comment] 2017-08-28 08:50
Duplicate of: https://github.com/asciidisco/plugin.video.netflix/issues/42

**Closed by asciidisco** 2017-08-28 08:50 UTC
Labels: duplicate
